async page => {
 const results=[];const check=(name,pass)=>{results.push({name,pass:!!pass});if(!pass)throw new Error(name+' failed');};
 const origin=page.url().split('/').slice(0,3).join('/');
 const route=async hash=>{await page.goto(origin+'/#'+hash);await page.locator('#role').waitFor();};
 const ready=()=>page.waitForFunction(()=>!document.querySelector('#loading'));
 await page.setViewportSize({width:1440,height:1000});
 await route('agent');const oldPassages=await page.locator('.agent-turn').first().locator('.readable-citation blockquote').allTextContents();
 await route('knowledge');await page.getByRole('button',{name:'Choose or drop a file',exact:true}).click();
 await page.locator('#quick-file').setInputFiles('scripts/browser/fixtures/synthetic-chat-journey.md');
 await page.locator('#quick-confirm').check();await page.getByRole('button',{name:'Parse document',exact:true}).click();
 await page.getByRole('button',{name:'Chat with this document in the sandbox →',exact:true}).waitFor();
 check('compiled upload parser leads directly to sandbox chat',true);
 await page.getByRole('button',{name:'Chat with this document in the sandbox →',exact:true}).click();await ready();
 check('sandbox context states its limited authority',(await page.locator('.knowledge-context').innerText()).includes('Selected for sandbox conversation'));
 check('upload confirmation is not repeated in chat',await page.locator('#agent-form input[type=checkbox]').count()===0);
 const count=await page.locator('.agent-turn').count();await page.getByRole('textbox',{name:'Message Pathway',exact:true}).fill('What does this document say?');await page.getByRole('textbox',{name:'Message Pathway',exact:true}).press('Enter');
 await page.waitForFunction(n=>document.querySelectorAll('.agent-turn').length===n+1&&document.querySelector('#agent-form')?.getAttribute('aria-busy')==='false',count);
 check('missing sandbox provider pauses without fallback',(await page.locator('.agent-turn').last().innerText()).includes('No fallback was used'));
 await route('knowledge');await page.getByRole('button',{name:'Use sample knowledge →',exact:true}).click();await ready();
 check('changing knowledge preserves governed conversation',await page.locator('.agent-turn').count()===count+1);
 await route('settings');check('office cannot approve settings',await page.getByRole('button',{name:'Approve defaults',exact:true}).isDisabled());
 await page.getByRole('combobox',{name:'Demo role',exact:true}).selectOption('supervisor');await ready();
 await page.locator('#setting-tone').selectOption('warm');await page.getByRole('button',{name:'Approve defaults',exact:true}).click();await ready();
 await page.reload();await page.locator('#setting-tone').waitFor();check('approved settings survive refresh',await page.locator('#setting-tone').inputValue()==='warm');
 await page.getByRole('combobox',{name:'Demo role',exact:true}).selectOption('office');await ready();
 await route('workspace');await page.getByRole('button',{name:'Identify missing documentation',exact:true}).click();await ready();
 await page.getByRole('button',{name:'Dispatch simulated follow-up',exact:true}).click();await ready();
 await page.getByRole('button',{name:'Introduce an ambiguity',exact:true}).click();await ready();
 await route('review');check('operational ambiguity retains a role-bound human task',await page.getByRole('button',{name:'Clarify and resume collection',exact:true}).isDisabled());
 await page.getByRole('combobox',{name:'Demo role',exact:true}).selectOption('manager');await ready();
 await page.getByRole('button',{name:'Clarify and resume collection',exact:true}).click();await ready();
 await page.getByRole('combobox',{name:'Demo role',exact:true}).selectOption('office');await ready();
 await route('workspace');await page.getByRole('button',{name:'Simulate document receipt',exact:true}).click();await ready();
 await route('review');await page.getByRole('button',{name:'Verify document and approve bound transfer',exact:true}).click();await ready();
 await route('workspace');await page.getByRole('button',{name:'Dispatch verified package',exact:true}).click();await ready();
 check('delivery remains separate from acknowledgement',await page.getByRole('button',{name:'Simulate receiving acknowledgment',exact:true}).isVisible());
 await page.getByRole('button',{name:'Simulate receiving acknowledgment',exact:true}).click();await ready();
 check('workflow still reaches documentation resolved with PA pending',(await page.locator('.boundary.complete').innerText()).includes('Prior authorization pending'));
 await route('studio');await page.locator('[data-source="K-PA"]').click();
 await page.getByRole('combobox',{name:'Demo role',exact:true}).selectOption('knowledge_reviewer');await ready();
 await page.getByRole('button',{name:'Retire this version',exact:true}).click();await page.getByRole('button',{name:'Confirm change',exact:true}).click();await ready();
 check('retirement control reflects completed action',await page.getByRole('button',{name:'Retirement recorded',exact:true}).isDisabled());
 await route('agent');const before=await page.locator('.agent-turn').count();await page.getByRole('textbox',{name:'Message Pathway',exact:true}).fill('What should happen next?');await page.getByRole('textbox',{name:'Message Pathway',exact:true}).press('Enter');
 await page.waitForFunction(n=>document.querySelectorAll('.agent-turn').length===n+1&&document.querySelector('#agent-form')?.getAttribute('aria-busy')==='false',before);
 check('retired source pauses future answer',await page.locator('.agent-turn').last().locator('.worker-turn.paused').count()===1);
 check('historical exact citations remain unchanged',JSON.stringify(await page.locator('.agent-turn').first().locator('.readable-citation blockquote').allTextContents())===JSON.stringify(oldPassages));
 await page.getByRole('textbox',{name:'Message Pathway',exact:true}).fill('MRN: 123456');await page.getByRole('textbox',{name:'Message Pathway',exact:true}).press('Enter');await page.locator('#composer-error:not([hidden])').waitFor();await route('studio');check('route-specific errors clear on navigation',await page.locator('#composer-error:not([hidden]),#inline-error:not([hidden])').count()===0);
 return {schema:'pathway-conversation-governance-browser-v1',timestamp:new Date().toISOString(),environment:'Local production build; provider unavailable sandbox pause; synthetic workflow only',results};
}
