import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { basename, extname, join, relative, resolve } from 'node:path';
import { FileEmbeddingCache } from '../src/providers/embedding.ts';

const root = resolve('.'), output = join(root, 'dist'), marker = '.pathway-build-v1';
if (!existsSync(join(root, 'tsconfig.build.json')) || JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).name !== 'pathway-agent') throw new Error('Run the build from the Pathway Agent repository root.');
if (existsSync(output) && (lstatSync(output).isSymbolicLink() || !existsSync(join(output, marker)))) throw new Error('Refusing to replace an unrecognized dist directory.');
const stage = mkdtempSync(join(root, '.pathway-build-'));
const walk = (directory: string): string[] => readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)).flatMap(entry => {
  const path = join(directory, entry.name);
  if (entry.isSymbolicLink()) throw new Error('Symlinks are not allowed in production assets.');
  return entry.isDirectory() ? walk(path) : entry.isFile() ? [path] : [];
});
try {
  const compile = spawnSync(process.execPath, [join(root, 'node_modules/typescript/bin/tsc'), '-p', 'tsconfig.build.json', '--outDir', stage], { cwd: root, stdio: 'inherit' });
  if (compile.status !== 0) throw new Error('Production TypeScript compilation failed.');
  const assets: Record<string, Set<string>> = { web: new Set(['.html','.js','.css','.svg','.png','.webp','.woff2']), fixtures: new Set(['.json']), migrations: new Set(['.sql']), config: new Set(['.crt']) };
  for (const [directory, extensions] of Object.entries(assets)) {
    for (const source of walk(join(root, directory))) {
      if (basename(source).startsWith('.')) continue;
      if (!extensions.has(extname(source))) continue;
      const destination = join(stage, relative(root, source)); mkdirSync(resolve(destination, '..'), { recursive: true }); copyFileSync(source, destination);
    }
  }
  const cache = new FileEmbeddingCache(join(stage, 'fixtures/embeddings'));
  const vectorFiles = walk(join(stage, 'fixtures/embeddings'));
  for (const file of vectorFiles) if (!await cache.get(basename(file, '.json'))) throw new Error('Missing packaged vector.');
  for (const required of ['src/app/server.js','src/app/service.js','scripts/db/cli.js','fixtures/knowledge/corpus.json','fixtures/retrieval/gold-v1.json','fixtures/retrieval/experiment-v1.json','web/index.html','web/app.js','web/styles.css']) {
    if (!existsSync(join(stage, required))) throw new Error(`Required production artifact missing: ${required}`);
  }
  const files = walk(stage).map(path => {
    const name = relative(stage, path).split('\\').join('/'), bytes = readFileSync(path);
    if (/(^|\/)(?:\.env(?:\.|$)|\.local|node_modules|artifacts|tests|\.git)(?:\/|$)/.test(name) || /\.(?:ts|pem|key|map)$/.test(name)) throw new Error('Disallowed file in production output.');
    if (['.js','.json','.html','.css','.sql','.svg','.crt'].includes(extname(path))) {
      const text = bytes.toString('utf8');
      if (/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|\bsk-(?:proj-)?[A-Za-z0-9_-]{30,}|postgres(?:ql)?:\/\/[^\s:"']+:[^\s@"']+@/.test(text)) throw new Error('Potential credential in build; inspect privately before packaging.');
      if (extname(path) === '.js' && /(?:from\s*|import\s*)["'][.]{1,2}\/[^"']+\.ts["']/.test(text)) throw new Error('Unrewritten TypeScript import in emitted artifact.');
    }
    return { path: name, bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex') };
  });
  const manifest = { schema: 'pathway-production-build-v1', synthetic: true, files, validatedEmbeddingRecords: vectorFiles.length, sourceMaps: false, secretsIncluded: false };
  writeFileSync(join(stage, 'build-manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  writeFileSync(join(stage, marker), 'Generated by scripts/build.ts. Replaced only by that build.\n');
  if (existsSync(output)) rmSync(output, { recursive: true });
  renameSync(stage, output);
  console.log(JSON.stringify({ status: 'built', files: files.length, validatedEmbeddingRecords: vectorFiles.length, manifest: 'dist/build-manifest.json' }));
} finally { if (existsSync(stage)) rmSync(stage, { recursive: true }); }
