import { readFileSync,readdirSync,writeFileSync } from 'node:fs';
import { textHash } from '../src/integrity.ts';
import { wordCount } from '../src/agent/turn-contract.ts';
const folder='artifacts/conversation/',casesBytes=readFileSync('scripts/browser/contextual-cases.json','utf8');
if(textHash(casesBytes)!=='b69c46bfc4ddda87afbe57c3b225d2b59cecd613692b60dbd1884a736e93ae26')throw new Error('FROZEN_CASES_CHANGED');
const cases=JSON.parse(casesBytes);
const reports=readdirSync(folder).filter(f=>/^contextual-(baseline|redesigned)-/.test(f)).map(path=>({path:folder+path,report:JSON.parse(readFileSync(folder+path,'utf8'))})).filter(x=>x.report.schema==='pathway-contextual-core-v1').sort((a,b)=>a.report.timestamp.localeCompare(b.report.timestamp));
const pick=(arm:string)=>reports.filter(x=>x.report.arm===arm).at(-1);
function metrics(x:ReturnType<typeof pick>){
 if(!x)return null;
 const r=x.report,turns=r.responses as any[],latencies=r.latencies.map((l:any)=>l.submissionToAnswerMs).sort((a:number,b:number)=>a-b),before=wordCount(turns[5]?.workProduct?.body??''),after=wordCount(turns[6]?.workProduct?.body??'');
 const inputTokens=turns.reduce((n,r)=>n+(r.audit?.inputTokens??0),0),outputTokens=turns.reduce((n,r)=>n+(r.audit?.outputTokens??0),0);
 return {artifact:x.path,turns:turns.length,exactPrompts:turns.length===cases.core.length&&turns.every((r,i)=>r.query===cases.core[i].text),acceptedTurns:turns.filter(r=>['answer','draft','recorded'].includes(r.disposition)).length,unnecessaryClarifications:turns.filter(r=>r.disposition==='clarify').length,pausedTurns:turns.filter(r=>r.disposition==='pause').length,mechanicalChecks:{passed:r.results.filter((c:any)=>c.pass).length,total:r.results.length,failures:r.results.filter((c:any)=>!c.pass).map((c:any)=>c.name)},emailWords:before,refinedWords:after,reductionPercent:before?(before-after)/before*100:null,smsCharacters:turns[8]?.workProduct?.body?.length??null,medianLatencyMs:latencies.length?latencies[Math.floor(latencies.length/2)]:null,maximumLatencyMs:latencies.at(-1)??null,reportedProviderRequests:turns.reduce((n,r)=>n+(r.audit?.requests??0),0),inputTokens,outputTokens,conservativeTokenEstimateUsd:(inputTokens*.4+outputTokens*1.6)/1e6,models:[...new Set(turns.filter(r=>r.audit?.requests).map(r=>r.audit.model))]};
}
const baseline=metrics(pick('baseline')),redesigned=metrics(pick('redesigned'));
const report={schema:'pathway-contextual-comparison-v1',timestamp:new Date().toISOString(),status:redesigned?'recorded_pending_semantic_review':'awaiting_redesigned_live_run',casesSha256:textHash(casesBytes),baselineRevision:'acaabee',baseline,redesigned,manualSemanticReview:null,
 caveats:['Exact twelve-prompt core comparison; developer-authored synthetic conversation, not an independent holdout.','Mechanical checks do not prove natural-language entailment or response usefulness; semantic review is separate.','Old bodies include their template subject and internal metadata; each shortening ratio compares that arm’s own body field.','Latency is end-to-end browser submission to saved display, including service/network effects. Cache and free-service cold starts may differ.','Reported generation requests/tokens exclude embedding usage and unreported failed-request tokens. A conservative September 9, 2026 estimate uses $0.40/M input and $1.60/M output, ignoring cache discounts; not a billing record.','The earlier boundary continuation is a reference trace; the new boundary scenario is separately isolated. Only the core is presented as an exact conversational pair.']};
const bytes=JSON.stringify(report,null,2)+'\n',path=folder+'comparison-'+textHash(bytes)+'.json';writeFileSync(path,bytes,{flag:'wx',mode:0o444});
const web=JSON.parse(readFileSync('web/evaluation.json','utf8'));web.contextualComparison={...report,artifact:path};writeFileSync('web/evaluation.json',JSON.stringify(web,null,2)+'\n');console.log(JSON.stringify({artifact:path,status:report.status,baseline,redesigned}));
