import { spawn } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { hash, textHash } from '../src/integrity.ts';

// Release verification uses the existing local profile and never reads provider
// secrets or makes live model calls. Frozen artifacts are checked, not rewritten.
if (process.env.PATHWAY_DATABASE_PROFILE && process.env.PATHWAY_DATABASE_PROFILE !== 'local-pg18-vector086') throw new Error('LOCAL_VERIFICATION_PROFILE_REQUIRED');
const walk=(dir:string):string[]=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(join(dir,e.name)):e.isFile()?[join(dir,e.name)]:[]);
const frozen=walk('artifacts').filter(p=>!p.startsWith('artifacts/digital-worker/') && !p.split('/').some(segment=>segment.startsWith('.'))).map(path=>({path,sha256:textHash(readFileSync(path,'utf8'))}));
const definitions=[['TypeScript contracts',['run','typecheck']],['Core governance and retrieval',['test']],['Original generation',['run','test:generation']],['Digital worker composition and conversational intent',['run','test:agent']],['Document parsing and safety',['run','test:studio']],['PostgreSQL persistence',['run','test:postgres']],['Workflow effects, roles and restart',['run','test:workflow']],['Application, isolation and Studio',['run','test:app']],['Original reference evaluation',['run','eval']],['Retirement and history demonstration',['run','demo']],['Retrieval probes',['run','probes']],['Cached PostgreSQL retrieval parity',['run','eval:postgres']]] as const;
mkdirSync('.local/worker-verification',{recursive:true});mkdirSync('artifacts/digital-worker',{recursive:true});
const suites:{name:string;command:string;passed:boolean;tests:number|null;durationMs:number;outputHash:string}[]=[];
for(const [name,args] of definitions){
 const start=performance.now();let output='';
 const command=name==='Application, isolation and Studio'?'node':'npm';
 const actualArgs=command==='node'?['scripts/db/with-verification.ts','app']:[...args];
 const code=await new Promise<number>(resolve=>{const child=spawn(command,actualArgs,{env:{...process.env,PATHWAY_LIVE_GENERATION:'disabled'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',data=>output+=data);child.stderr.on('data',data=>output+=data);child.once('error',()=>resolve(1));child.once('exit',c=>resolve(c??1));});
 const count=output.match(/(?:ℹ|#) tests (\d+)/),row={name,command:command+' '+actualArgs.join(' '),passed:code===0,tests:count?Number(count[1]):null,durationMs:performance.now()-start,outputHash:textHash(output)};
 suites.push(row);writeFileSync('.local/worker-verification/'+name.replace(/[^A-Za-z0-9]/g,'-')+'.log',output,{mode:0o600});
 console.log(JSON.stringify(row));if(code!==0){console.log(output.slice(-8000));process.exitCode=1;break;}
}
const frozenUnchanged=frozen.every(f=>textHash(readFileSync(f.path,'utf8'))===f.sha256);
const report={schema:'pathway-digital-worker-verification-v1',timestamp:new Date().toISOString(),environment:'Local Node 24 / PostgreSQL 18 / pgvector 0.8.6; isolated synthetic fixtures',summary:suites.every(s=>s.passed)&&suites.length===definitions.length&&frozenUnchanged?'All recorded automated suites passed. Live model quality was not measured in this run.':'Verification has an incomplete or failing check. See the recorded suites.',suites,frozenArtifacts:{count:frozen.length,unchanged:frozenUnchanged,manifestHash:hash(frozen)},
 retrieval:{model:'OpenAI text-embedding-3-small, 1536 dimensions · preserved real synthetic vectors',summary:'The frozen 36-question benchmark measured lexical 31/36 and semantic/hybrid 36/36 correct outcomes. The persistence suite replays 108 comparisons plus the 23 original references.',limitations:'Developer-authored synthetic cases, no independent holdout. Cached replay measures ranking/governance reproducibility; it is not fresh-provider quality, fair cold latency or new-upload quality.'},
 generation:{model:'Optional OpenAI gpt-4.1-mini-2025-04-14 · pathway-contextual-v1; replaceable provider interface',summary:'Contextual interpretation and complete-turn contracts, full-text review coverage, transformation constraints, durable regeneration, feedback, legacy composition and fail-closed checks were exercised with explicit fixtures. No live synthesis quality score is claimed.',cost:'No live model requests were made by this verification. Incremental model cost: $0. Historical embedding benchmark: 3,435 tokens, estimated $0.0000687 at its September 7 rate; cache order prevents fair cost comparison.'},
 limitations:['All cases, identities and integrations are synthetic. No real outreach, payer approval or clinical authority.','Live synthesis and new semantic vectors require explicitly configured server credentials and request budgets. Missing or failed providers pause with no silent fallback.','Model support review is fallible. Exact quote and eligibility checks do not prove every paraphrase is entailed.','TXT, Markdown, PDF and DOCX parsing is bounded: 1 MB, 20 PDF pages, 64,000 extracted characters and 128 passages. No OCR; PDF tables can have uncertain reading order.','Content screening and user attestation do not guarantee patient-data detection. Temporary sandbox data expires with the session; approved published sources and governed evidence remain immutable.','Enterprise identity, real channel integrations, independent healthcare validation, production load, backup restoration and patient outcomes are unverified.']};
const bytes=JSON.stringify(report,null,2)+'\n',artifact='artifacts/digital-worker/verification-'+textHash(bytes)+'.json';writeFileSync(artifact,bytes,{flag:'wx',mode:0o444});writeFileSync('web/evaluation.json',bytes);console.log(JSON.stringify({artifact,frozenUnchanged}));if(!frozenUnchanged)process.exitCode=1;
