import type { KnowledgePack, PackId, Passage } from './contracts.ts';

export const packs: KnowledgePack[] = [
 { id:'alder', name:'Alder Prior Authorization Knowledge Pack', shortName:'Alder documentation', version:'1.1', scenario:'HCP office documentation support',
 description:'Find the missing document and prepare a clear office follow-up.', user:{name:'Avery Chen',role:'HCP office access coordinator',email:'avery.chen@alder-office.example'},
 agentRole:'Documentation Support Agent',caseId:'ALD-1042',caseContext:'Synthetic case ALD-1042 at Alder HCP Office. Request N-101 remains open against submitted package PKG-1042. No payer decision is recorded.',
 caseSummary:'Alder HCP Office submitted package PKG-1042. Request N-101 is still open; no payer decision is recorded.',
 blocker:'The package contains an unsigned office note. The signed note, including its signature page, is still missing.',
 covers:['Missing-document requests','Document quality checks','Receipt and reconciliation','Office follow-up examples','Case handoffs and escalation','Administrative next steps'],
 prompts:['What document is missing?','Why is it being requested?','Is there a deadline?','Draft a short email requesting the document.'],workProduct:'An office email requesting the signed note',
 recipient:{name:'Alder HCP Office',email:'access@alder-office.example'},defaultChannel:'chat'},
 { id:'access',name:'Synthetic Coverage and Access Knowledge Pack',shortName:'Coverage & access',version:'1.1',scenario:'Field reimbursement support',
 description:'Turn an access roadblock into a useful HCP-office briefing.',user:{name:'Morgan Lee',role:'field reimbursement manager',email:'morgan.lee@cedar-support.example'},
 agentRole:'Access Support Agent',caseId:'ACC-2086',caseContext:'Synthetic case ACC-2086 for Cedar Support and fictitious Juniper Plan. Benefit verification is incomplete because the member identifier is unreadable. No prior authorization submission or coverage determination is recorded.',
 caseSummary:'Cedar Support is checking benefits with fictitious Juniper Plan. No prior-authorization submission or coverage determination is recorded.',
 blocker:'The member identifier on the submitted insurance card is unreadable, so benefit verification is incomplete.',
 covers:['Member-information checks','Benefit-verification records','Prior-authorization preparation','Discrepancy troubleshooting','Office briefings and follow-ups','Escalation and support boundaries'],
 prompts:['What is blocking this case?','What can I tell the HCP office?','What remains unknown?','Summarize this case for my next office conversation.'],workProduct:'A concise case briefing or office follow-up email',
 recipient:{name:'Cedar HCP Office',email:'access@cedar-office.example'},defaultChannel:'email'},
 { id:'fulfillment',name:'Synthetic Specialty Pharmacy Fulfillment Knowledge Pack',shortName:'Specialty pharmacy fulfillment',version:'1.1',scenario:'Patient-support fulfillment',
 description:'Explain a fulfillment status in language a patient can understand.',user:{name:'Jordan Rivera',role:'patient-support case manager',email:'jordan.rivera@willow-support.example'},
 agentRole:'Fulfillment Support Agent',caseId:'FUL-3091',caseContext:'Synthetic case FUL-3091 for Willow Support and fictitious Birch Specialty Pharmacy. Enrollment is received, consent signature is missing, and prescription intake is recorded. There is no dispense release or carrier handoff.',
 caseSummary:'Willow Support has received enrollment, and fictitious Birch Specialty Pharmacy has recorded prescription intake. No dispense release or carrier handoff is recorded.',
 blocker:'The consent form is missing its required signature. The case is not dispense-ready.',
 covers:['Consent completion checks','Prescription-intake handoffs','Dispense and shipment milestones','Conflicting status reports','Patient communication examples','Administrative escalation'],
 prompts:['Where is this case in the fulfillment process?','What is still needed?','Has the medication shipped?','Draft a patient-friendly status update.'],workProduct:'A patient-friendly administrative status message',
 recipient:{name:'Taylor Sample (synthetic patient)',email:'taylor.sample@patient.example'},defaultChannel:'chat'},
];
export const getPack = (id: PackId) => packs.find(p=>p.id===id)!;
type Document = { id: string; packId: PackId; title: string; type: string; version: string; status: 'current'|'superseded'; caseId: string|null; sections: Array<[string,string]> };
const doc = (packId:PackId,id:string,title:string,type:string,sections:Array<[string,string]>,caseId:string|null=null,status:'current'|'superseded'='current',version='1.0'):Document => ({packId,id,title,type,sections,caseId,status,version});
export const documents: Document[] = [
 doc('alder','N-101','N-101 · Signed office note request','Case-specific request',[
 ['Requested item','For synthetic case ALD-1042, request N-101 asks the Alder HCP Office for the signed office note referenced in its submitted package. The signature page must be part of the note. A cover sheet or an unsigned note does not satisfy this request.'],
 ['Reason and timing','The signed office note is requested to complete the administrative documentation package identified in N-101. This request does not say that treatment is appropriate or that prior authorization will be approved. N-101 specifies no response deadline, due date or urgency.']], 'ALD-1042'),
 doc('alder','INV-1042','PKG-1042 · Submitted-package inventory','Document inventory',[
 ['Received package','The synthetic PKG-1042 inventory lists the request cover sheet, demographic form and unsigned office note. It does not list a signed office note or signature page.'],
 ['Receipt record','As of the synthetic case snapshot on September 10, 2026 at 10:00 AM, there is no later receipt acknowledgment for the signed note. A request being created is not evidence that a document was received.']], 'ALD-1042'),
 doc('alder','PROC-01','Missing-document follow-up guide','Process guide',[
 ['Office next step','Ask the office to provide the complete signed note through its established secure document channel and reference case ALD-1042 and request N-101. The Knowledge Pack does not contain an actual upload URL, fax number or secure-channel address. Do not place patient records in an ordinary email.'],
 ['After submission','After the office reports submission, check for a receiving-team acknowledgment. The receiving team checks whether the requested signed note and signature page are present. Only its acknowledgment can confirm receipt; receipt alone does not confirm package completeness or a payer decision.']]),
 doc('alder','COM-01','Office communication guide','Communication guide',[
 ['Draft guidance','A useful synthetic office email identifies the signed office note requested in N-101, explains that it completes the requested documentation package, and asks for submission through the established secure channel. Thank the office and offer administrative help. Do not invent a deadline, urgency, receipt confirmation or approval promise.'],
 ['Recorded office reply','The synthetic office message at 9:15 AM on September 10, 2026 says: “We sent the cover sheet and unsigned note. We are checking with the clinician about the signature.” This is the recorded office report; it does not prove a signed note was sent or received.']], 'ALD-1042'),
 doc('alder','FAQ-01','Receipt, completion and decisions','FAQ',[
 ['Different milestones','Document sent means the office reports transmission. Received means the receiving team acknowledges arrival. Complete means the required package has been checked. Prior authorization approved means a payer has made an approval decision. These milestones are distinct; do not infer one from another.'],
 ['Authority limits','Pathway provides administrative support only. The payer decides prior authorization and coverage. Pathway cannot recommend treatment, determine clinical necessity, promise eligibility or approval, or send a real email.']]),
 doc('alder','ESC-01','Documentation escalation guide','Escalation guide',[
 ['Unknowns and escalation','If the request is unclear, ask the receiving support team to clarify the exact missing item. If the office reports submission but no acknowledgment is available, ask that team to check receipt. The pack defines no universal waiting period or acknowledgment service-level deadline.']]),
 doc('alder','ARCH-01','Archived office-note reminder','Superseded procedure',[
 ['Superseded guidance','This archived 2025 reminder used a five-business-day response target. It was superseded by PROC-01 and does not apply to request N-101. Do not use it to establish a deadline for ALD-1042.']],null,'superseded','0.8'),
 doc('alder','OTHER-77','N-077 · Separate case request','Inapplicable case request',[
 ['Different case','Synthetic case ALD-9999 request N-077 needs an insurance card by September 15, 2026. This request is unrelated to ALD-1042 and must not define its required document or deadline.']], 'ALD-9999'),
 doc('access','BV-2086','ACC-2086 · Benefit-verification status','Status record',[
 ['Current blocker','For synthetic case ACC-2086, benefit verification is incomplete because the member identifier on the submitted Juniper Plan insurance card is unreadable. The office should confirm the identifier or provide a legible copy through its established secure channel. No benefit result is recorded.'],
 ['Known and unknown','The prescriber name and demographic form are on file. Active benefits, prior-authorization requirements, patient cost, network specialty pharmacy and coverage outcome remain unknown. No prior-authorization submission or payer decision is recorded.']], 'ACC-2086'),
 doc('access','BV-GUIDE','Benefit-verification process','Process guide',[
 ['Administrative sequence','Obtain legible member and plan information, confirm the identity fields with the office, and submit a benefit-verification inquiry through the authorized support channel. Record the returned benefit information and its date before explaining case-specific requirements. A verification request is not a coverage approval.'],
 ['Timing','The synthetic access pack does not specify a benefit-verification turnaround guarantee or a deadline for the office to respond. Do not promise a completion date.']]),
 doc('access','PA-GUIDE','Prior-authorization administrative steps','Process guide',[
 ['Before submission','After current benefits and any prior-authorization requirement are confirmed, identify the applicable payer form and documentation, help the office assemble the package, submit through the authorized channel and track the payer acknowledgment. Only the payer can determine whether authorization is required and whether to approve it.']]),
 doc('access','JUN-01','Juniper Plan administrative checklist','Synthetic policy summary',[
 ['Common documentation','This synthetic Juniper checklist lists a legible member identifier, prescriber details and a completed payer form as common administrative inputs when a prior-authorization request is required. It is general guidance, not confirmation that a particular service is covered or that ACC-2086 requires authorization.'],
 ['Policy support and limits','The legible member identifier requirement is supported by this checklist and the ACC-2086 status record. Additional clinical documentation depends on the applicable payer request and must be confirmed; the pack supplies no treatment criteria or medical-necessity determination.']]),
 doc('access','OFFICE-2086','Office support conversation record','Communication record',[
 ['Office statement','In the synthetic September 10, 2026 office exchange, staff reported: “The card image is blurry. We can check the member number and send a clearer copy.” No corrected identifier or new card receipt is recorded.'],
 ['Briefing and follow-up','For the next office conversation, explain the unreadable member identifier, request a legible card or confirmed identifier through the established secure channel, and say benefit verification can proceed once the required information is available. Distinguish that next administrative step from a benefit or authorization result.']], 'ACC-2086'),
 doc('access','ACCESS-ESC','Access support escalation and boundaries','Escalation guide',[
 ['Who to contact','Route unresolved benefit-verification discrepancies to the support program benefit-verification team. Route payer interpretation, exception or appeal questions to the payer or appropriate office specialist. A field reimbursement manager can explain the documented process and organize questions, but cannot overturn a payer decision.'],
 ['No unsupported promises','Do not predict approval, promise financial-assistance eligibility, give a patient-cost amount, recommend treatment or claim an email was sent. These are outside this synthetic administrative support demonstration.']]),
 doc('access','JUN-OLD','Archived Juniper phone-verification note','Superseded policy',[
 ['Retired rule','A retired 2025 guide said every Juniper case required prior authorization and quoted a two-day verification target. JUN-01 and BV-GUIDE supersede it. Neither claim should be applied to the current case.']],null,'superseded','0.7'),
 doc('access','OTHER-2087','ACC-2087 · Separate verified case','Inapplicable status record',[
 ['Different case','For synthetic ACC-2087 only, the returned benefit record says prior authorization is required and an office response is due September 18, 2026. ACC-2087 is not ACC-2086; this result cannot answer the selected case.']], 'ACC-2087'),
 doc('fulfillment','STATUS-3091','FUL-3091 · Fulfillment status','Status record',[
 ['Current stage','For synthetic case FUL-3091, Willow Support enrollment is received and Birch Specialty Pharmacy has recorded prescription intake. The consent form is missing its required signature. The case is not dispense-ready. No dispense release, shipment confirmation, carrier handoff or tracking number is recorded.'],
 ['Next administrative item','The missing item is the signed consent form. Jordan can explain how to complete consent through the established secure program channel and ask the intake team to confirm receipt and completeness. No real channel address or patient record belongs in this demo.']], 'FUL-3091'),
 doc('fulfillment','ENROLL-01','Enrollment and consent prerequisites','Program terms',[
 ['Consent requirement','A completed enrollment form and the required signed consent are administrative prerequisites for advancing the synthetic support enrollment. A submitted or received form is not necessarily complete. Missing consent must be resolved and its receipt checked; do not claim that resolution alone guarantees dispensing.']]),
 doc('fulfillment','RX-01','Prescription intake and dispense readiness','Process guide',[
 ['Intake sequence','Prescription intake means the pharmacy recorded the prescription for review. The pharmacy must complete its required checks and confirm dispense readiness. Pathway can describe recorded administrative stages but cannot validate a prescription, decide treatment, release medication or override pharmacy checks.']]),
 doc('fulfillment','SHIP-01','Pharmacy shipment-status glossary','Status glossary',[
 ['Shipment terms','Label created means shipping information was prepared; it does not confirm carrier possession. Shipped or carrier handoff requires an explicit shipment confirmation. Delivered requires a delivery confirmation. Intake received, enrollment received and dispense-ready do not mean shipped.'],
 ['Dates and promises','This synthetic Knowledge Pack provides no shipment date, delivery estimate, processing turnaround guarantee or deadline for FUL-3091 consent. Only the pharmacy or carrier can confirm its own actual status; the support program must not promise delivery.']]),
 doc('fulfillment','PATIENT-01','Patient-friendly status communication','Communication guide',[
 ['Suggested content','Explain that enrollment has been received and prescription intake is recorded, but a signature on the consent form is still needed. Ask the patient to complete consent through the established secure program channel. Say the pharmacy must complete its checks before shipment can be confirmed. Keep language calm and concise; do not promise a delivery date or recommend treatment.'],
 ['Recorded patient question','The synthetic patient message reads: “I filled out the enrollment form. Does that mean it is on the way?” This is a question, not a shipping confirmation.']], 'FUL-3091'),
 doc('fulfillment','FUL-ESC','Pharmacy escalation and support limits','Escalation guide',[
 ['Escalation','Contact the specialty pharmacy intake team if consent receipt is unclear, intake details conflict, or the patient reports a shipment that is absent from the record. Ask the pharmacy to confirm the administrative stage and missing items. Clinical or medication questions belong with the treating clinician or pharmacist.'],
 ['Authority','Pathway cannot promise dispensing, financial-assistance eligibility, delivery or clinical outcomes. Drafts are generated for review and never sent. There is no automatic outreach or actual pharmacy integration.']]),
 doc('fulfillment','FUL-OLD','Archived shipping quick reference','Superseded glossary',[
 ['Retired shortcut','A retired 2025 quick reference used “label created” as “shipped” and suggested next-day arrival. SHIP-01 supersedes that wording. Do not infer carrier handoff or delivery from a label.']],null,'superseded','0.6'),
 doc('fulfillment','OTHER-3092','FUL-3092 · Separate shipped case','Inapplicable status record',[
 ['Different case','Synthetic case FUL-3092 has a confirmed carrier handoff and an estimated September 14, 2026 delivery. It is unrelated to FUL-3091 and cannot establish shipping or delivery for the selected case.']], 'FUL-3092'),
 // Additive 1.1 sources keep the original passage IDs and text immutable.
 // These fictional procedures add depth without changing the recorded case state.
 doc('alder','DOC-QA','Signed-note preparation checklist','Synthetic operations guide',[
 ['Pages and legibility','In the fictional Alder documentation process, the office checks the complete note before submitting it: all pages are present, page edges are not cropped, the text is readable, and the signature page belongs to the same note. A cover sheet helps route the package but cannot replace a missing page or signature. If the scan is incomplete, obtain a complete copy from the office record; do not recreate clinical text or a signature.'],
 ['Document identity','For a signed-note resubmission, the office compares the document description with the open request and confirms that the pages belong to the intended case using its secure records. Use the case and request references on the routing cover sheet. Do not add patient identifiers to an ordinary follow-up email. If two notes or versions could match the request, ask the receiving team which document it needs before submitting unrelated records.'],
 ['Signature questions','The Alder pack requests a signed office note including its signature page, but it does not define accepted electronic-signature formats, countersignature rules or who may sign on a clinician’s behalf. Those questions require clarification from the receiving team and the office’s authorized staff. A typed name or an unsigned copy must not be treated as accepted solely because it is readable. Pathway cannot authenticate a signature or decide whether clinical documentation is sufficient.'],
 ['Pre-submission review','A useful office checklist is: confirm the requested note, check every page, include the signature page, check scan legibility, reference the open case/request, and use the established secure document channel. Keep a submission reference if that channel provides one. This checklist describes preparation; it does not establish that the note has been submitted, received or accepted. The pack provides no actual upload link, fax number or maximum file-size rule.']],null,'current','1.1'),
 doc('alder','RECEIPT-LOG','Submission and receipt reconciliation','Synthetic operations guide',[
 ['Submission log fields','When the office reports sending a document in the fictional Alder process, an administrative log can capture the case/request reference, document description, submitting office, reported submission time, channel used and any transmission reference. Label these as office-reported details until the receiving team confirms them. A transmission receipt may help locate a package; it is not the receiving team’s completeness review. Only record values actually supplied, leaving absent details unknown.'],
 ['Matching an acknowledgment','To reconcile an acknowledgment, compare its case reference, request reference, document description and receipt details with the submission report. An acknowledgment for a cover sheet, a different case or an earlier package does not establish receipt of the newly requested signed note. If an acknowledgment says only “package received,” ask whether the complete signed note and signature page were included and whether review is still pending.'],
 ['Sent but not found','If the office says it sent the note and the receiving team cannot locate it, ask the office for the reported time, channel and transmission reference through the appropriate support process. Ask the receiving team to check routing and document association. Confirm the correct secure route before coordinating another submission, and label a replacement so the team can reconcile duplicates. No automatic resend or fixed waiting period is specified by this pack.'],
 ['Closing the documentation question','Keep submission, receipt, completeness review and payer decision as separate milestones. If receipt is confirmed but completeness is pending, report exactly that. If the receiving team identifies a missing page, document that discrepancy and the next owner rather than describing the request as resolved. Even confirmed documentation completeness does not establish prior-authorization approval. The support record should link any status change to the team acknowledgment that actually supports it.']],null,'current','1.1'),
 doc('alder','NOTE-ISSUES','Office-note troubleshooting playbook','Synthetic troubleshooting guide',[
 ['Only an unsigned copy is available','If the office has only an unsigned copy, clarify that the open request is for the signed note and its signature page. Ask the office to coordinate with its authorized clinician or documentation staff. Do not ask support staff to sign for the clinician, paste a signature onto the note or alter clinical content. If the office cannot obtain the requested document, route that limitation to the receiving team for an explicit next step.'],
 ['A partial or unreadable copy arrives','If a receiving-team report identifies a missing page, cropped signature or unreadable text, request a readable complete copy of the specific document. Describe the observed defect rather than adding unrelated requirements. Keep the earlier receipt record and the new correction request distinct: something may have been received without satisfying the request. Do not infer that all pages are acceptable from a successful file transmission.'],
 ['The office disputes the request','If office staff believe the requested note was already supplied, compare the submitted-package inventory, the office’s transmission report and the receiving acknowledgment. Ask which exact document and version each party is discussing. If the disagreement remains, request clarification from the receiving support team. An office statement is useful evidence of what the office reports; it does not by itself overwrite the receiving record or prove administrative completeness.'],
 ['A deadline or exception is requested','If someone asks for a due date, expedited handling or an alternative document, check the current case request for explicit instructions. Request N-101 contains no deadline or urgency, and the pack defines no substitution rule. Ask the receiving team to clarify an exception request; do not apply the archived five-business-day reminder or a different case’s deadline. A request for faster handling is not evidence that expedited processing has been accepted.']],null,'current','1.1'),
 doc('alder','DOC-HANDOFF','Documentation ownership and handoff worksheet','Synthetic handoff guide',[
 ['Who owns each step','In the fictional Alder process, the HCP office obtains the requested signed document and submits it through its established secure channel. The receiving support team locates the submission, acknowledges receipt and checks whether the requested items are present. The office access coordinator organizes follow-up and records confirmed updates. Clinical authorship remains with authorized clinical staff, and a payer decision remains with the payer; the coordinator does not assume either role.'],
 ['A useful handoff record','A documentation handoff should identify the case/request, the exact missing item, what the inventory already contains, the latest attributed office report, the next responsible team, the requested confirmation and the unresolved questions. Include a submission or acknowledgment reference only if one exists. Avoid “all set” as a status label when receipt or completeness is still unknown. A named next owner explains who should respond without claiming that outreach has occurred.'],
 ['An escalation request that can be acted on','A useful request to the receiving team asks a precise question: clarify the document requested, locate a reported submission, identify a missing page, or confirm whether a received note satisfies the administrative request. Supply relevant case and transmission references through the secure support process. Ask for the team’s finding and the next administrative step. Do not include a speculative payer outcome, a fabricated service-level deadline or an unsupported clinical justification.'],
 ['Updating a colleague','A concise colleague update separates three things: confirmed record, attributed report, and next action. For example, “The inventory does not show the requested signed note. The office reports checking with the clinician about the signature. Next, request the complete signed note and seek receiving-team acknowledgment after submission.” That example is a draft based on the recorded Alder snapshot, not a new contact event or confirmation that the office has completed the task.']],null,'current','1.1'),
 doc('alder','OFFICE-TEMPLATES','Office correspondence examples','Synthetic communication examples',[
 ['Initial signed-note request example','Example draft for ALD-1042, not sent: Subject: Signed office note for request N-101. Body: “Hello Alder HCP Office, the requested signed office note, including its signature page, is still missing from the documentation package for N-101. Please provide the complete signed note through your established secure document channel and reference ALD-1042 / N-101. Thank you for helping complete the requested documentation. Please let us know if you need clarification about the requested item.”'],
 ['Follow-up after reported submission','Conditional example, to use only if the office actually reports submission: “Thank you for the update. Could you confirm the submission reference and reported time through the established support channel? We will use those details to ask the receiving team to locate the signed note and confirm whether the signature page is present.” This is draft wording for a future follow-up. It does not establish that the note was sent, that a search occurred or that the receiving team acknowledged it.'],
 ['Requesting clarification without blame','Example clarification draft, not sent: “We want to make sure the correct document reaches the team. Could you confirm whether N-101 requires the complete signed office note and its signature page, and advise how to resolve any remaining document discrepancy?” Keep the message focused on the document question. Avoid accusing the office of failing to respond, adding a due date absent from the request, or asking for unrelated clinical records.'],
 ['Shortening or warming a message','When refining an Alder office email, preserve the requested signed note, signature page, case/request references and secure-channel instruction. A warmer message may add a brief thank-you; a shorter message can omit repeated background. Neither style change should introduce urgency, a deadline or an approval promise. Keep citations and retrieval notes outside the recipient-facing email body, and retain the distinction between a generated draft and a message actually sent.']], 'ALD-1042','current','1.1'),
 doc('alder','ALD-BRIEF','ALD-1042 · Recorded case briefing','Synthetic case companion',[
 ['Snapshot and evidence map','The recorded Alder snapshot concerns ALD-1042, submitted package PKG-1042 and open request N-101. N-101 specifies the signed office note with its signature page. INV-1042 lists a cover sheet, demographic form and unsigned office note. COM-01 contains the office report that staff are checking with the clinician about the signature. Read those sources together; this companion organizes the existing record and adds no later submission, receipt or payer event.'],
 ['Objective and immediate blocker','Avery Chen’s administrative objective is to help the office supply the item requested in N-101 and obtain a clear receiving-team record. The immediate blocker is the missing signed office note and signature page. An unsigned note already in the package does not satisfy the request. The next useful office discussion should confirm how to provide the complete signed note through the established secure channel, without asking Avery to validate clinical content.'],
 ['Questions for the next office conversation','Useful questions for the next Alder office conversation are: Can the office obtain the complete signed note and signature page? Is any part of the request unclear? If submission is reported, what reference can the receiving team use to locate it? These are proposed questions, not answers already in the record. No later signed-note receipt, request deadline, acceptance of an alternative document or payer decision is supplied by this snapshot.'],
 ['What a later update would need','A later status update would need evidence of the relevant milestone: an office report for reported submission, a receiving-team acknowledgment for receipt, and a receiving-team review for documentation completeness. A payer decision would require its own payer record. Until such information exists, continue to describe the signed-note request as open. A conversation with Pathway or a generated email cannot create those events or change the scenario’s recorded snapshot.']], 'ALD-1042','current','1.1'),
 doc('access','MEMBER-QA','Member-information reconciliation checklist','Synthetic operations guide',[
 ['Reading the card accurately','For the fictional Cedar benefit-verification process, use a readable member identifier and plan information supplied through the established secure channel. Ask the office to resolve ambiguous characters rather than guessing whether a mark is a zero, letter O or another character. A clearer image should show the relevant card information without cropped fields or glare. The pack supplies no universal member-number length or validation pattern, so format alone cannot confirm accuracy.'],
 ['Conflicting member information','If the card image and office record contain different identifiers or plan names, describe the discrepancy and ask the office to confirm which information is current. Preserve the source and date of each report while the issue is being resolved. Do not choose an identifier based on similarity, silently overwrite it, or assume that a readable older card reflects active coverage. Unresolved discrepancies belong with the support program benefit-verification team.'],
 ['Requesting just the missing input','A focused request identifies the unreadable field and asks for a confirmed identifier or legible card through the established secure channel. Ask the office whether the relevant plan information has changed instead of requiring it to resend unrelated records. Do not place a full member number, card image or patient demographics in an ordinary email or this public demo. The Knowledge Pack does not contain a real secure-upload URL or destination fax number.'],
 ['Before resuming verification','After corrected information is supplied, the benefit-verification team should confirm that the input is usable, associate it with the intended case and resume the authorized inquiry. Record the source of the correction and the inquiry status. Receiving a clearer card resolves an information-quality question; it does not establish active benefits, patient cost, a prior-authorization requirement or coverage approval. Those conclusions require the appropriate current returned information.']],null,'current','1.1'),
 doc('access','BENEFIT-RECORD','Returned-benefit review worksheet','Synthetic operations guide',[
 ['Recording a returned response','When a benefit-verification response is available in the fictional Cedar process, record its source, response date, case association, plan identity, scope of the inquiry, reference number if supplied, and exactly which questions it answers. Keep unanswered fields marked unknown. This worksheet specifies how to document a response; it does not assert that ACC-2086 has received one. A submitted inquiry and a returned result are different milestones.'],
 ['Checking scope and currency','Before explaining a benefit result, confirm that it applies to the intended plan, member, requested service and relevant date. An old result or a result for a different service should not be presented as current case-specific guidance. If the response is ambiguous about its scope, ask the benefit-verification team or payer to clarify. Do not generalize one returned result to every Juniper case or treat another case’s response as evidence for ACC-2086.'],
 ['Separating access questions','A returned response may address active benefits, whether prior authorization is required, where a prescription may be filled, or patient responsibility. Treat each as a separate question and record only what the response actually states. A confirmed benefit does not by itself establish prior-authorization approval, pharmacy acceptance or a final patient cost. For ACC-2086 those fields remain unknown in the recorded snapshot because no benefit result is present.'],
 ['Cost and assistance questions','If an office asks what the patient will pay or whether assistance is available, first identify what current payer or program information is actually available. The synthetic Cedar pack contains no patient-cost amount, assistance eligibility criteria, award decision or guarantee. Route cost interpretation to the appropriate benefit-verification or payer contact and assistance questions to the relevant program team. Do not quote an amount or promise eligibility from a general process checklist.']],null,'current','1.1'),
 doc('access','PA-PACKET','Prior-authorization preparation and acknowledgment','Synthetic operations guide',[
 ['Confirm the requirement first','Prior-authorization packet preparation in the fictional Cedar process follows confirmation of current benefits and any applicable authorization requirement. Record who supplied that requirement and which service it covers. If a requirement has not been confirmed, prepare questions for the payer or benefit-verification team instead of describing a submission as necessary or underway. For ACC-2086, no authorization requirement or prior-authorization submission is recorded.'],
 ['Organize the applicable packet','If authorization is confirmed as required, the office can identify the applicable current payer form, legible member information, prescriber details and any specifically requested supporting documentation. Compare the packet against that request and flag unanswered fields to the responsible office staff. The general Juniper checklist is a starting point, not proof of a complete case-specific requirement set. The pack provides no clinical treatment criteria, medical-necessity judgment or list of universally required clinical attachments.'],
 ['Submission and payer acknowledgment','If the authorized office submits a prior-authorization packet, record its reported date, channel and reference if provided, then distinguish that report from the payer’s acknowledgment. An acknowledgment means the payer received the identified request; it is not approval. If the payer identifies an incomplete field, ask the responsible office staff to address that specific request and preserve the updated submission history. Pathway does not submit forms or contact the payer in this demo.'],
 ['Additional information, exceptions and appeals','If a payer asks for additional information or communicates a decision, preserve the exact request or decision, its date, and any explicitly stated response instructions. Route interpretation, exceptions and appeal preparation to the payer or appropriate office specialist. Do not infer an appeal window, denial reason or expedited-review entitlement from general guidance. The current ACC-2086 record contains no payer decision or case-specific appeal instructions to explain.']],null,'current','1.1'),
 doc('access','ACCESS-ISSUES','Benefit-verification troubleshooting and routing','Synthetic troubleshooting guide',[
 ['A readable card still does not resolve the inquiry','If a corrected card remains unusable or the inquiry returns a mismatch, compare the specific discrepancy with the office’s confirmed information and ask the benefit-verification team to investigate. A mismatch does not by itself establish that the patient is uninsured or that a service is excluded. Record the returned wording and the question needing resolution. Do not create a replacement identifier or claim that an unsuccessful inquiry is a payer denial.'],
 ['The office reports a plan change','A reported plan change is a reason to ask for current plan information through the established secure channel and have the benefit-verification team determine which inquiry should be made. Preserve the distinction between the office’s report and confirmed returned benefits. Do not carry forward a prior plan’s authorization requirement, network pharmacy or cost estimate without current support. No plan change is recorded for ACC-2086; this is conditional troubleshooting guidance.'],
 ['The office asks for a completion estimate','Explain what input is outstanding and which team owns the next step, then ask the benefit-verification team whether it can provide a case-specific status update. The current Cedar and Juniper guidance supplies no guaranteed turnaround or office response deadline. Avoid converting an informal follow-up plan into a promised completion date. The archived two-day phone-verification target does not apply to the current process or establish a commitment for ACC-2086.'],
 ['Escalation handoff fields','A useful benefit-verification escalation contains the case reference, specific discrepancy, source of the conflicting information, steps already confirmed, the unanswered question and the team asked to respond. Pass sensitive identifiers only through the appropriate secure support process. Ask for a documented finding and next administrative step. A field reimbursement manager can coordinate that handoff and explain the record, but cannot change a payer determination or promise a coverage result.']],null,'current','1.1'),
 doc('access','ACCESS-TEMPLATES','HCP-office access conversation examples','Synthetic communication examples',[
 ['Clearer-card request example','Example draft for ACC-2086, not sent: Subject: Member information for benefit verification. Body: “Hello Cedar HCP Office, benefit verification remains incomplete because the Juniper Plan member identifier is unreadable on the submitted card. Please confirm the identifier or provide a legible copy through your established secure channel, referencing ACC-2086. Once the required information is usable, the benefit-verification team can proceed with the inquiry. Thank you for your help.” No benefit result or completion date is implied.'],
 ['Brief office-call agenda','For Morgan’s next ACC-2086 office conversation, a useful agenda is: confirm the unreadable member identifier is the immediate blocker; ask how the office will provide a confirmed identifier or clearer card; identify the benefit-verification team as owner of the inquiry; and list the results still needed before discussing case-specific requirements. Close by checking whether the office needs clarification about the requested input. This is a proposed agenda, not a record of a completed call.'],
 ['Answering the approval question','Example wording for the current ACC-2086 record: “We do not have a coverage or authorization result yet. The immediate step is to resolve the unreadable member identifier so the benefit-verification inquiry can proceed. Once the relevant information is returned, the team can explain what it confirms and what remains open.” This message separates process progress from payer authority and avoids presenting the general Juniper checklist as a requirement already confirmed for this case.'],
 ['A concise escalation note','Conditional escalation draft, not sent: “Please review the member-information discrepancy for the referenced case, confirm which input is needed to proceed, and advise the next administrative step. The office-reported details and available submission references are included through the secure support channel.” Populate actual references only when supplied. Do not invent an inquiry date, member number, prior contact attempt or payer response to make the message appear more complete.']], 'ACC-2086','current','1.1'),
 doc('access','ACC-BRIEF','ACC-2086 · Recorded access briefing','Synthetic case companion',[
 ['Snapshot and evidence map','ACC-2086 concerns Cedar Support and fictional Juniper Plan. BV-2086 records incomplete benefit verification caused by an unreadable member identifier; prescriber details and the demographic form are on file. OFFICE-2086 records the office’s statement that the image is blurry and it can check the member number or send a clearer copy. No corrected identifier, new card receipt or returned benefit result is recorded. This briefing organizes those existing facts only.'],
 ['Objective and decision sequence','Morgan Lee’s objective is to help the HCP office resolve the input problem and understand the next administrative step. First obtain usable member information; then the authorized benefit-verification inquiry can proceed. Current returned information is needed before explaining case-specific prior-authorization requirements, cost or network pharmacy. The general Juniper checklist supports asking for a legible identifier, but it does not establish that this case requires authorization or that any service is covered.'],
 ['Known facts and open questions','For the ACC-2086 briefing, the known blocker is the unreadable card identifier, and the known office report is that staff can check it. Open questions include receipt of a correction, active benefits, prior-authorization requirement, patient cost, network specialty pharmacy and coverage outcome. No prior-authorization submission or payer decision is recorded. Keep these unknowns visible instead of filling them with another Juniper case’s result, a historical rule or a model-generated assumption.'],
 ['What would support a later status update','An office confirmation or legible card receipt would support an update about corrected input. A returned benefit record with its source and date would support only the benefit details it actually states. A payer acknowledgment or decision would support its own separate milestone. None of those events is created by chatting with Pathway or drafting an email. The sidebar and this briefing remain the scenario’s recorded snapshot until the source catalog is deliberately updated.']], 'ACC-2086','current','1.1'),
 doc('fulfillment','CONSENT-QA','Consent completion and receipt checklist','Synthetic operations guide',[
 ['Explain the outstanding item','In the fictional Willow program, the required consent signature is a separate administrative item from the enrollment form being received. Explain which item is missing in plain language and direct the person to the established secure program process. Do not infer consent from a completed enrollment form, a patient question or prescription intake. For FUL-3091, the current record identifies the missing signature; it does not report a later completed consent.'],
 ['Questions about signing','The Willow pack does not define accepted electronic-signature methods, proxy authority, guardian documentation, witness requirements or a particular consent platform. If the patient asks who may sign or whether a signature method is accepted, refer the question to the program intake team for the applicable instructions. Support staff must not sign on someone’s behalf or treat a typed name as accepted without confirmation. This guide describes the fictional administrative process, not legal consent advice.'],
 ['Checking a submitted consent form','If signed consent is reported as submitted, ask the intake team to confirm receipt, association with the intended case, legibility and whether the required signature is present under its process. Keep the patient’s submission report distinct from the team’s finding. If a page or signature is still missing, explain that specific discrepancy and the secure correction route. Do not mark enrollment complete solely because a file upload or transmission was successful.'],
 ['After consent is confirmed','If intake confirms the required consent is complete, record that finding and ask which administrative steps remain. Consent completion does not automatically establish dispense readiness, medication release or shipment. The pharmacy must complete its own checks and confirm its stage. FUL-3091 currently contains no consent-completion confirmation, dispense release or carrier handoff, so a hypothetical next step must not be written as if it has already happened.']],null,'current','1.1'),
 doc('fulfillment','INTAKE-HANDOFF','Program-to-pharmacy handoff worksheet','Synthetic handoff guide',[
 ['Separate program and pharmacy roles','In the fictional Willow/Birch process, program intake confirms enrollment and consent items; pharmacy intake records the prescription and manages pharmacy review. A support case manager explains the documented administrative status and coordinates questions. A clinician or pharmacist handles clinical and medication questions. Neither the support program nor Pathway can release a prescription, override pharmacy review or promise that resolving one program item satisfies every pharmacy requirement.'],
 ['Useful handoff fields','A program-to-pharmacy handoff can identify the case reference, enrollment receipt status, consent status, recorded prescription-intake stage, latest source for each status, the specific unresolved item and the question for the next team. Include a date or contact reference only when documented. Keep reported submission, confirmed receipt and completeness distinct. Sharing this worksheet as a draft does not transmit patient records or establish that the pharmacy has received a handoff.'],
 ['Questions for pharmacy intake','Useful pharmacy-intake questions are: Which administrative stage is confirmed? Are any program or intake items outstanding? Has dispense readiness been confirmed? Is there an explicit release or shipment record? Ask for the source and date of the status being provided. Do not turn these questions into assumed answers. If the question concerns prescription validity, medication use, storage or treatment, refer it to the pharmacist or treating clinician rather than answering from an administrative checklist.'],
 ['Recording the response','When a team provides an update, attribute it to that team and record which milestone it supports. For example, consent receipt can be confirmed while completeness review remains open, or pharmacy intake can be recorded while release remains unconfirmed. Preserve separate unknowns rather than combining them into “ready.” A useful next-action entry names the team and the confirmation requested; it does not claim that a call, transfer or shipment has occurred.']],null,'current','1.1'),
 doc('fulfillment','FUL-ISSUES','Consent and intake troubleshooting','Synthetic troubleshooting guide',[
 ['The patient says they already signed','If a patient reports completing consent while the intake record still shows a missing signature, thank them for the update and ask the intake team to reconcile the report with the case. A reported completion time or submission reference may help locate the form if available. Do not ask the person to post the form in an ordinary email or public chat. Until confirmed, describe this as a reported submission with receipt or completeness still being checked.'],
 ['A form was received but is incomplete','If intake confirms a form was received but identifies a missing signature or unreadable section, explain that exact issue and ask the team for the established secure correction instructions. Avoid saying that no form was received when the problem is completeness. Do not assume a new full enrollment is required, invent a form expiry date or prescribe a signature method absent from the program’s instructions. A correction request does not itself resolve the missing item.'],
 ['The patient cannot use the stated process','If the patient cannot access or use the established consent process, ask the intake team what supported alternative or administrative assistance is available. The pack does not list an alternate portal, telephone-consent option, mailing address or proxy-signature rule. Do not invent one or recommend ordinary email for patient records. Keep the request for assistance separate from consent completion, and avoid promising that an alternative will be accepted before the team confirms it.'],
 ['Records or reports conflict','If program intake, pharmacy intake and the patient describe different stages, retain each attributed report and ask the relevant team to reconcile the discrepancy. Clarify whether each report concerns enrollment, consent, prescription intake, dispense release or shipment. An older or differently scoped update may not answer the current question. Do not select the most advanced status merely because it sounds reassuring, and do not apply another patient’s shipping record to FUL-3091.']],null,'current','1.1'),
 doc('fulfillment','SHIPMENT-CHECK','Shipment evidence and status reconciliation','Synthetic operations guide',[
 ['Evidence for each milestone','In the fictional Birch status process, prescription intake means the prescription is recorded for review. Dispense readiness and release each need pharmacy confirmation. Label creation means shipping information is prepared. Carrier handoff needs an explicit shipment confirmation, and delivery needs a delivery confirmation. Keep the milestone, reporting organization and source date together. A label, intake receipt or complete enrollment cannot be substituted for evidence of carrier possession.'],
 ['A tracking number or shipment is reported','If a patient reports a tracking number or says the order shipped but the case record lacks a shipment event, ask the pharmacy to confirm whether the report belongs to the intended case and what milestone is supported. If the carrier has a record, its reported status should be distinguished from pharmacy preparation. Do not manufacture a tracking link, infer delivery from an identifier, or mark FUL-3091 shipped based only on the patient’s question.'],
 ['Delivery estimates and exceptions','An estimate, if actually supplied by the pharmacy or carrier, should retain its source and be described as an estimate rather than a promise. A delay, failed delivery or address discrepancy should be routed to the organization responsible for that status through its established support process. The FUL-3091 pack supplies no estimate, carrier, tracking number or delivery exception. It cannot answer medication-storage or missed-dose questions; those belong with the pharmacist or clinician.'],
 ['Answering the current shipping question','For FUL-3091, explain that enrollment receipt and prescription intake are recorded, but consent lacks its required signature and no dispense release or carrier handoff is recorded. Shipment therefore cannot be confirmed from this snapshot. Ask the intake team about consent and the pharmacy about its own stage when an updated confirmation is needed. Avoid implying that signing consent will automatically trigger dispatch or establish a delivery date.']],null,'current','1.1'),
 doc('fulfillment','PATIENT-TEMPLATES','Patient status-message examples','Synthetic communication examples',[
 ['Calm status-update example','Example draft for the recorded FUL-3091 snapshot, not sent: “Hello Taylor, your enrollment has been received and the pharmacy has recorded prescription intake. A signature on the consent form is still needed. Please complete that step through the established secure program channel; the intake team can help if you need clarification. The pharmacy still needs to complete its checks before shipment can be confirmed. We do not have a confirmed shipment or delivery date in this record.”'],
 ['Reply to a reported consent submission','Conditional example, only after a patient reports submitting consent: “Thank you for letting us know. The next step is to ask the intake team to confirm that the signed consent was received and is complete. That confirmation is separate from the pharmacy’s review and shipment status.” This is suggested wording for a future reply. It does not establish that the program checked receipt, that the form is complete or that the medication is on its way.'],
 ['Explaining received versus shipped','Example response to “I filled out the enrollment form. Does that mean it is on the way?”: “Enrollment received means the program has your enrollment information. It does not mean the pharmacy has released a shipment. In this recorded case, the consent signature is still missing, and there is no confirmed carrier handoff.” Keep the explanation administrative and patient-friendly. Do not add medical advice, a delivery estimate or an assurance that all pharmacy checks have passed.'],
 ['Refining for tone and clarity','For a warmer or shorter patient message, retain the recorded stage, missing consent signature, secure next step and uncertainty about shipment. Replace internal jargon with plain language, such as “the pharmacy has recorded the prescription for review” for intake. Avoid “approved,” “on the way,” or “arriving soon” unless an appropriate current source supports that milestone. Keep evidence citations outside the recipient-facing message and label the work product as generated for review.']], 'FUL-3091','current','1.1'),
 doc('fulfillment','FUL-BRIEF','FUL-3091 · Recorded fulfillment briefing','Synthetic case companion',[
 ['Snapshot and evidence map','The FUL-3091 snapshot concerns Willow Support and fictional Birch Specialty Pharmacy. STATUS-3091 records enrollment receipt, missing consent signature and prescription intake, with no dispense release or carrier handoff. PATIENT-01 records the patient’s question about whether enrollment means the medication is on the way. ENROLL-01, RX-01 and SHIP-01 explain the distinct administrative milestones. This companion organizes that record and adds no later consent, dispensing or shipping event.'],
 ['Objective and immediate blocker','Jordan Rivera’s objective is to explain the current administrative position and help identify the next confirmation needed. The immediate recorded item is the required consent signature. Jordan can direct the patient to the established secure program process and ask intake to confirm receipt and completeness. Jordan cannot complete consent for the patient, validate a prescription, authorize dispensing or turn a draft status message into actual pharmacy outreach.'],
 ['Questions that remain open','The recorded FUL-3091 case does not establish signed-consent receipt or completeness, dispense readiness, dispense release, shipment confirmation, carrier possession, tracking or delivery date. Useful follow-up questions ask intake about consent and the pharmacy about its stage. Do not interpret the patient’s enrollment question as evidence of shipment. The separate FUL-3092 shipping record and retired label-created shortcut cannot answer the selected case.'],
 ['What supports a later status update','A later consent update needs an intake-team finding; a later pharmacy-stage update needs pharmacy confirmation; carrier possession and delivery need the corresponding shipment or delivery record. Describe only the milestone that the source establishes and retain outstanding questions about later stages. Conversations, generated drafts and conditional process examples do not update the recorded scenario. In the present snapshot, consent is still missing and shipment remains unconfirmed.']], 'FUL-3091','current','1.1'),
];
// Each focused section is a separately retrievable passage. Exact strings are canonical.
export const passages: Passage[] = documents.flatMap(d=>d.sections.map(([section,text],i)=>({
 id:`${d.packId}.${d.id}.${i+1}`,packId:d.packId,caseId:d.caseId,sourceId:d.id,title:d.title,type:d.type,version:d.version,status:d.status,section,text,synthetic:true as const,
})));
