const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label = s => String(s ?? '').replaceAll('_',' ').replace(/^./, c => c.toUpperCase()).replace(/\bCrm\b/g,'CRM').replace(/\bSms\b/g,'SMS');
const date = s => s ? new Date(s).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Denver'}) : 'No pending checkpoint';
const raw = (name, value) => `<details class="advanced"><summary>${esc(name)}</summary><pre>${esc(JSON.stringify(value,null,2))}</pre></details>`;
let selectedOperation = 'ask', selectedChannel = 'chat', selectedAudience = 'case_manager', pending = null;
const sourceName = (view,c) => view.knowledge.documents.find(d => d.id === c.documentId)?.title ?? c.documentId;
function exactCitations(view,entry) {
 return entry.citations.map((c,i) => `<details class="readable-citation"><summary><span class="citation-number">${i+1}</span>${esc(sourceName(view,c))}</summary><blockquote>${esc(c.text)}</blockquote><p class="small muted">Exact source text · ${esc(c.locator.section)} · lines ${c.locator.lineStart}–${c.locator.lineEnd}</p>${raw('Passage locator and hashes',c)}</details>`).join('');
}
function answer(view,e) {
 const evidence=view.evidence.find(r=>r.id===e.evidenceId),assignment=view.knowledge.assignments.find(a=>a.id===view.knowledge.activeAssignmentId);
 const changed=(evidence&&assignment&&evidence.selectedReleases.some(r=>!assignment.releaseIds.includes(r.id)))||e.workflowRevision!==view.workflow.revision || e.citations.some(c=>view.knowledge.events.some(v=>['retirement','supersession'].includes(v.type)&&v.targetId===c.documentVersionId));
 const clarification = e.clarification?.status === 'open' && !view.agent.entries.some(x => x.clarification?.status === 'resolved' && x.inReplyTo === e.id);
 return `<article class="agent-turn" id="turn-${esc(e.id)}"><div class="user-turn"><span class="eyebrow">You · Synthetic ${esc(label(e.operation))}</span><p>${esc(e.query)}</p></div><div class="worker-turn ${e.disposition==='pause'?'paused':''}"><div class="row"><span class="worker-identity"><img src="/mark.svg" alt="">Pathway Agent</span><span class="small muted">${date(e.timestamp)}</span></div><p class="answer-lead">${esc(e.message)}</p>${changed?'<p class="message warn small">Historical answer. The case or supporting source has changed; ask again for a current evidence and permission check.</p>':''}<p class="generation-label">${e.audit.method==='model-synthesis'?'Generated synthesis · exact citations checked · model support review is fallible':e.audit.method==='provider-pause'?'Provider paused · no fallback':'Generated from deterministic case and evidence rules · no language model'}</p>
 ${clarification?`<div class="clarification-box"><p>${esc(e.clarification.why)}</p><div class="buttons">${e.clarification.options.map(o=>`<button data-clarify="${esc(e.id)}" data-choice="${o.value}">${esc(o.label)}</button>`).join('')}</div><small>Clarifies this conversation. Operational decisions still require the assigned reviewer.</small></div>`:''}
 ${!['recorded','clarify'].includes(e.disposition)?`<div class="answer-next"><p><strong>Next:</strong> ${esc(e.context.nextAction)}</p><p class="small">${esc(e.context.owner)} · Action permission at answer time: ${esc(label(e.context.permission.action))}</p><a href="${view.workflow.tasks.some(t=>t.status==='open')?'#review':'#workspace'}">Review the next step →</a></div>`:''}
 ${e.analysis?`<div class="analysis-grid"><div><span>Administrative tone</span><strong>${esc(label(e.analysis.sentiment))}</strong></div><div><span>Reported urgency</span><strong>${esc(label(e.analysis.urgency))}</strong></div><div><span>Likely intent</span><strong>${esc(label(e.analysis.intent))}</strong></div></div><p class="small">Supporting language: ${e.analysis.supportingLanguage.map(x=>`<q>${esc(x)}</q>`).join(', ')||'No clear administrative cue'}. Confidence: ${esc(e.analysis.confidence)}.</p><details><summary>Uncertainty and interpretation limits</summary><p>${esc(e.analysis.uncertainty)}</p></details>`:''}
 ${e.claims.filter(c=>!c.id.startsWith('case-status')).map(c=>`<p class="grounded-claim"><span class="claim-type">${esc(label(c.kind))}</span>${esc(c.text)} <span class="source-refs">${c.supports.map(s=>e.citations.findIndex(c=>c.passageId===s.reference)+1).filter(i=>i>0).filter((i,n,a)=>a.indexOf(i)===n).map(i=>`[${i}]`).join(' ')}</span></p>`).join('')}
 ${e.workProduct?`<section class="work-product"><div class="row"><h3>${esc(label(e.workProduct.type))} · ${esc(label(e.workProduct.audience))}</h3><span class="pill warn">Draft · not sent</span></div><p class="small muted">${esc(label(e.workProduct.channel))} · ${esc(e.workProduct.tone)} · ${esc(e.workProduct.purpose)}</p><label for="draft-${esc(e.id)}" class="small">Review or edit the generated text</label><textarea id="draft-${esc(e.id)}" class="draft-editor" maxlength="8000">${esc(e.workProduct.body)}</textarea><div class="buttons"><button data-save-draft="${esc(e.id)}">Save edited version</button><button data-copy-draft="${esc(e.id)}">Copy draft</button></div><p class="small muted">Editing does not authorize sending. The case workspace dispatches only its approved generic simulation template.</p>${raw('Required and omitted content', {required:e.workProduct.requiredContent,omitted:e.workProduct.omittedContent,status:e.workProduct.status,basedOn:e.workProduct.basedOn})}</section>`:''}
 ${e.citations.length?`<div class="citation-list"><h3>Sources behind this answer</h3>${exactCitations(view,e)}</div>`:''}
 <details class="advanced"><summary>Evidence, permissions and generation details</summary><dl class="kv"><dt>Source support</dt><dd>${esc(label(e.context.permission.sourceSupport))}</dd><dt>Case applicability</dt><dd>${esc(label(e.context.permission.applicability))}</dd><dt>Communication</dt><dd>${esc(label(e.context.permission.communication))}</dd><dt>Action permission</dt><dd>${esc(label(e.context.permission.action))}</dd></dl>${e.evidenceId?`<button data-evidence="${esc(e.evidenceId)}">Open immutable evidence record</button>`:''}${raw('Claim support and authoritative facts',e.claims)}${raw('Generation audit and raw output',e.audit)}${raw('Reason codes', [...new Set(e.reasonCodes)])}</details></div></article>`;
}
export function renderAgent(view) {
 const state=view.agent, entries=state?.entries.filter(e=>e.conversationId===state.activeConversationId)||[], latest=entries.at(-1), next=view.currentAgentContext;
 const pendingTask=view.workflow.tasks.find(t=>t.status==='open');
 return `<div class="page-heading"><div><div class="eyebrow">Your digital case worker</div><h1>One case. A continuing conversation.</h1><p>Ask, clarify and prepare the next step—with evidence and a memory you can inspect.</p></div><button data-new-conversation>New conversation</button></div>
 <div class="agent-layout"><section class="conversation-column" aria-label="Case conversation"><div class="conversation-stream" aria-live="polite" aria-relevant="additions">${entries.length?entries.map(e=>answer(view,e)).join(''):`<div class="agent-welcome"><img src="/mark.svg" alt=""><h2>I’ll keep the follow-through in view.</h2><p>We’re working on synthetic case DEMO-101. I can explain the documentation dependency, prepare a handoff, and keep track of what needs a human decision.</p><div class="suggestions"><button data-agent-suggestion="What is the next step for this case?">What should happen next?</button><button data-agent-suggestion="Which clinician-authenticated encounter narrative remains outstanding?">Explain the missing document</button><button data-agent-suggestion="Is it ready?">Show a clarifying question</button></div></div>`}</div>
 <form id="agent-form" class="agent-composer"><div class="composer-settings"><div class="field"><label for="agent-operation">I want to</label><select id="agent-operation">${[['ask','Ask about the case'],['summary','Create a case summary'],['draft','Draft a communication'],['interaction','Record a synthetic interaction']].map(([v,t])=>`<option value="${v}" ${v===selectedOperation?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label for="agent-channel">Channel</label><select id="agent-channel">${['chat','email','sms','voice','teams'].map(v=>`<option value="${v}" ${v===selectedChannel?'selected':''}>${v==='teams'?'Teams transcript':v==='voice'?'Voice transcript':label(v)}</option>`).join('')}</select></div><div class="field"><label for="agent-audience">Audience</label><select id="agent-audience">${[['case_manager','Case manager'],['office','Office / HCP staff'],['supervisor','Internal supervisor'],['crm','CRM activity note']].map(([v,t])=>`<option value="${v}" ${v===selectedAudience?'selected':''}>${t}</option>`).join('')}</select></div></div><label for="agent-text">Your question, drafting purpose, or synthetic message</label><textarea id="agent-text" rows="3" maxlength="2000" placeholder="What does the case need next, and who is responsible?"></textarea><div class="composer-options"><label for="agent-tone">Tone<select id="agent-tone"><option value="concise">Concise</option><option value="warm">Warm</option><option value="formal">Formal</option></select></label><label for="agent-generation">Composition<select id="agent-generation"><option value="evidence">Case and evidence rules</option><option value="model">Live model synthesis${state?.provider.enabled?'':' · not configured'}</option></select></label></div><label class="check-label"><input id="agent-synthetic" type="checkbox" required>I’m using synthetic administrative content, with no real patient information or secrets.</label><div class="row mt-16"><small class="muted">Saved to this isolated case. ${state?.provider.enabled?'Live calls use bounded server budgets.':'Uncached semantic questions pause until a provider is configured.'}</small><button type="submit" class="primary">Continue conversation</button></div></form></section>
 <aside class="agent-context stack"><section class="card"><div class="eyebrow">Case in focus</div><h2>DEMO-101</h2><span class="pill ${view.workflow.state==='PAUSED'?'warn':''}">${esc(label(view.workflow.state))}</span><dl class="kv mt-20"><dt>Current owner</dt><dd>${esc(next?.owner??'Pathway Agent')}</dd><dt>Next checkpoint</dt><dd>${date(next?.checkpoint)}</dd><dt>Permission</dt><dd>Rechecked before every action</dd></dl><div class="context-next"><span class="eyebrow">Recommended next step</span><p>${esc(next?.nextAction??'Assess the documentation dependency')}</p><small>${esc(next?.why??'The case is ready for its first governed assessment.')}</small></div><a class="context-link" href="${pendingTask?'#review':'#workspace'}">${pendingTask?'Open assigned human task':'Open case controls'} →</a></section>
 <section class="card"><h3>Memory you can inspect</h3><p class="small muted">Case facts come from governed evidence and the workflow. Conversation adds context; it cannot change those facts.</p><details><summary>Authoritative case record</summary>${raw('Workflow facts, decisions and effects',{state:view.workflow.state,revision:view.workflow.revision,decisions:view.workflow.decisions,effects:view.workflow.effects,tasks:view.workflow.tasks})}</details><details><summary>Conversation context · ${entries.length} entries</summary>${entries.filter(e=>['interaction','clarify'].includes(e.operation)).map(e=>`<p class="small"><strong>Unverified context:</strong> ${esc(e.query)}</p>`).join('')||'<p class="small muted">No channel interactions or resolved clarifications yet.</p>'}</details><details><summary>Earlier conversations · ${state?.conversations.filter(c=>c.archived_at).length||0}</summary>${state?.conversations.filter(c=>c.archived_at).map(c=>`<details><summary>Conversation from ${date(c.created_at)}</summary>${state.entries.filter(e=>e.conversationId===c.id).map(e=>`<p class="small"><strong>${esc(e.query)}</strong><br>${esc(e.message)}</p>${raw('Historical response with exact evidence',e)}`).join('')}</details>`).join('')||'<p class="small muted">Starting a conversation preserves this history.</p>'}</details></section>
 <section class="boundary"><h3>The completion boundary</h3><p>Documentation dependency resolved; prior authorization pending.</p><small>Recommendations, permission and execution remain separate. Every channel and identity here is synthetic.</small></section></aside></div>`;
}
export function bindAgent({view,api,perform,refresh,render,toast}) {
 const $=s=>document.querySelector(s);
 const submit=async payload=>{
  const fingerprint=JSON.stringify(payload);
  if(!pending||pending.fingerprint!==fingerprint)pending={fingerprint,idempotencyKey:crypto.randomUUID()};
  await api('/api/agent',{...payload,synthetic:true,idempotencyKey:pending.idempotencyKey}); pending=null;
  await refresh(); render(); const answer=document.querySelector('.agent-turn:last-child .answer-lead'); if(answer){answer.tabIndex=-1;answer.focus();}else $('#agent-text')?.focus();
 };
 $('#agent-operation')?.addEventListener('change',e=>{selectedOperation=e.target.value;});
 $('#agent-channel')?.addEventListener('change',e=>{selectedChannel=e.target.value;});
 $('#agent-audience')?.addEventListener('change',e=>{selectedAudience=e.target.value;});
 $('#agent-form')?.addEventListener('submit',e=>{e.preventDefault();const text=$('#agent-text').value.trim();perform(()=>submit({operation:selectedOperation,...(text?{text}:{}),channel:selectedChannel,audience:selectedAudience,tone:$('#agent-tone').value,generation:$('#agent-generation').value}),'Conversation saved.');});
 document.querySelectorAll('[data-agent-suggestion]').forEach(b=>b.addEventListener('click',()=>{$('#agent-text').value=b.dataset.agentSuggestion;$('#agent-text').focus();}));
 $('[data-new-conversation]')?.addEventListener('click',()=>perform(()=>submit({operation:'new_conversation'}),'New conversation ready. Case history preserved.'));
 document.querySelectorAll('[data-clarify]').forEach(b=>b.addEventListener('click',()=>perform(()=>submit({operation:'clarify',targetId:b.dataset.clarify,choice:b.dataset.choice}),'Clarification recorded and current evidence checked.')));
 document.querySelectorAll('[data-save-draft]').forEach(b=>b.addEventListener('click',()=>perform(()=>submit({operation:'edit_draft',targetId:b.dataset.saveDraft,text:document.getElementById('draft-'+b.dataset.saveDraft).value}),'Edited draft saved.')));
 document.querySelectorAll('[data-copy-draft]').forEach(b=>b.addEventListener('click',()=>perform(async()=>{await navigator.clipboard.writeText(document.getElementById('draft-'+b.dataset.copyDraft).value);toast('Draft copied. Nothing was sent.');})));
}
