const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label = s => String(s ?? '').replaceAll('_',' ').replace(/^./, c => c.toUpperCase()).replace(/\bCrm\b/g,'CRM').replace(/\bSms\b/g,'SMS');
const date = s => s ? new Date(s).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Denver'}) : 'No pending checkpoint';
const raw = (name, value) => `<details class="advanced"><summary>${esc(name)}</summary><pre>${esc(JSON.stringify(value,null,2))}</pre></details>`;
const drafts = new Map();
let pending = null, sending = false, composerError = '', progressLabel='Understanding your message…';
const stageLabels={understanding:'Understanding your message…',retrieving:'Checking current knowledge…',composing:'Writing the response…',validating:'Validating the complete response…'};
export const agentPending = () => sending;
const draftKey = view => view.demoId + ':' + (view.agent.knowledge?.key ?? 'unavailable');
const sourceName = (view,c) => view.knowledge.documents.find(d => d.id === c.documentId)?.title ?? c.documentId;
function exactCitations(view,entry) {
 return entry.citations.map((c,i) => `<details class="readable-citation"><summary><span class="citation-number">${i+1}</span>${esc(entry.knowledge?.sourceNames?.[c.documentId] ?? sourceName(view,c))}</summary><blockquote>${esc(c.text)}</blockquote><p class="small muted">Exact source text · ${esc(c.locator.section)} · lines ${c.locator.lineStart}–${c.locator.lineEnd}</p>${raw('Passage locator and hashes',c)}</details>`).join('');
}
function answer(view,e) {
 const evidence=e.temporaryEvidence??view.evidence.find(r=>r.id===e.evidenceId),assignment=view.knowledge.assignments.find(a=>a.id===view.knowledge.activeAssignmentId);
 const changed=(evidence&&assignment&&evidence.selectedReleases.some(r=>!assignment.releaseIds.includes(r.id)))||e.workflowRevision!==view.workflow.revision || e.citations.some(c=>view.knowledge.events.some(v=>['retirement','supersession'].includes(v.type)&&v.targetId===c.documentVersionId));
 const clarification = e.clarification?.status === 'open' && !view.agent.entries.some(x => x.clarification?.status === 'resolved' && x.inReplyTo === e.id);
 return `<article class="agent-turn" id="turn-${esc(e.id)}"><div class="user-turn"><span class="eyebrow">You · Synthetic ${esc(label(e.operation))}</span><p>${esc(e.query)}</p></div><div class="worker-turn ${e.disposition==='pause'?'paused':''}"><div class="row"><span class="worker-identity"><img src="/mark.svg" alt="">Pathway Agent</span><span class="small muted">${date(e.timestamp)}</span></div><p class="answer-lead">${esc(e.message)}</p>${e.turn?.rationale?`<p class="answer-rationale">${esc(e.turn.rationale)}</p>`:''}${e.interpretation?.note?`<p class="small muted">${esc(e.interpretation.note)}</p>`:''}${e.knowledge?.kind==='upload'?'<p class="small sandbox-label">Temporary document exploration · No case or action authority</p>':''}${changed?'<p class="message warn small">Historical answer. The case or supporting source has changed; ask again for a current evidence and permission check.</p>':''}<p class="generation-label">${e.audit.method==='model-synthesis'?'Generated answer · Review the cited evidence':e.audit.method==='provider-pause'?'Provider paused · no fallback':'Evidence-based answer · Review before use'}</p>
 ${clarification?`<div class="clarification-box"><p>${esc(e.clarification.why)}</p><div class="buttons">${e.clarification.options.map(o=>`<button data-clarify="${esc(e.id)}" data-choice="${o.value}">${esc(o.label)}</button>`).join('')}</div><small>Clarifies this conversation. Operational decisions still require the assigned reviewer.</small></div>`:''}
 ${!['recorded','clarify'].includes(e.disposition)?`<details class="answer-next"><summary>Next step and case context</summary><p><strong>Next:</strong> ${esc(e.context.nextAction)}</p><p class="small">${esc(e.context.owner)} · Action permission at answer time: ${esc(label(e.context.permission.action))}</p><a href="${view.workflow.tasks.some(t=>t.status==='open')?'#review':'#workspace'}">Review the next step →</a><p class="small">Checkpoint: ${date(e.context.checkpoint)}</p><p class="small">Target completion boundary: ${esc(e.context.completionBoundary)}</p></details>`:''}
 ${e.analysis?`<div class="analysis-grid"><div><span>Administrative tone</span><strong>${esc(label(e.analysis.sentiment))}</strong></div><div><span>Reported urgency</span><strong>${esc(label(e.analysis.urgency))}</strong></div><div><span>Likely intent</span><strong>${esc(label(e.analysis.intent))}</strong></div></div><p class="small">Supporting language: ${e.analysis.supportingLanguage.map(x=>`<q>${esc(x)}</q>`).join(', ')||'No clear administrative cue'}. Confidence: ${esc(e.analysis.confidence)}.</p><details><summary>Uncertainty and interpretation limits</summary><p>${esc(e.analysis.uncertainty)}</p></details>`:''}
 ${e.claims.filter(c=>!e.turn && !e.workProduct && !c.id.startsWith('case-status') && c.text!==e.message).map(c=>`<p class="grounded-claim"><span class="claim-type">${esc(label(c.kind))}</span>${esc(c.text)} <span class="source-refs">${c.supports.map(s=>e.citations.findIndex(c=>c.passageId===s.reference)+1).filter(i=>i>0).filter((i,n,a)=>a.indexOf(i)===n).map(i=>`[${i}]`).join(' ')}</span></p>`).join('')}
 ${e.workProduct?`<section class="work-product"><div class="row"><h3>${esc(label(e.workProduct.type))} · ${esc(label(e.workProduct.audience))}</h3><span class="pill warn">Generated · not sent</span></div>${e.workProduct.subject?`<p class="product-subject"><strong>Subject:</strong> ${esc(e.workProduct.subject)}</p>`:''}<div class="product-text">${esc(e.workProduct.body)}</div><div class="product-actions"><button data-copy-draft="${esc(e.id)}">Copy</button><button data-product-prompt="Make that shorter." data-target="${esc(e.id)}">Shorten</button><button data-product-prompt="Make that warmer." data-target="${esc(e.id)}">Change tone</button><button data-product-prompt="Turn it into an SMS." data-target="${esc(e.id)}">Convert to SMS</button><button data-memory-product="${esc(e.id)}">Save to case memory</button><button data-review-product="${esc(e.id)}">Prepare for simulated review</button><button data-inspect-product="${esc(e.id)}">Inspect supporting evidence</button></div><details class="product-edit"><summary>Edit generated text</summary><label for="draft-${esc(e.id)}">Your revised draft</label><textarea id="draft-${esc(e.id)}" class="draft-editor" maxlength="8000">${esc(e.workProduct.body)}</textarea><button data-save-draft="${esc(e.id)}">Save edited version</button></details><p class="small muted">Saved conversational work product. No authoritative fact, CRM record, communication or workflow action is created.</p>${raw('Required and omitted content', {required:e.workProduct.requiredContent,omitted:e.workProduct.omittedContent,status:e.workProduct.status,basedOn:e.workProduct.basedOn})}</section>`:''}
 ${e.citations.length?`<details class="citation-list"><summary>Sources behind this answer (${e.citations.length})</summary>${exactCitations(view,e)}</details>`:''}
 <div class="turn-feedback">${e.turn&&e.knowledge?.key===view.agent.knowledge?.key&&!['interaction','clarify'].includes(e.disposition)?`<button data-regenerate="${esc(e.id)}" ${view.agent.entries.filter(x=>x.turn?.regeneratedFrom===(e.turn.regeneratedFrom??e.id)).length>=2?'disabled title="Two regenerations used"':''}>Regenerate</button>`:''}${(view.agent.feedback??[]).some(f=>f.entry_id===e.id)?'<span class="small muted">Feedback recorded. Thank you.</span>':`<button data-feedback="${esc(e.id)}" data-rating="helpful" aria-label="Helpful answer">Helpful</button><button data-feedback="${esc(e.id)}" data-rating="not_helpful" aria-label="Not helpful answer">Not helpful</button>`}</div>
 <details class="advanced"><summary>Evidence, permissions and generation details</summary><dl class="kv"><dt>Source support</dt><dd>${esc(label(e.context.permission.sourceSupport))}</dd><dt>Case applicability</dt><dd>${esc(label(e.context.permission.applicability))}</dd><dt>Communication</dt><dd>${esc(label(e.context.permission.communication))}</dd><dt>Action permission</dt><dd>${esc(label(e.context.permission.action))}</dd></dl>${e.temporaryEvidence?raw('Temporary evidence record · expires with this document',e.temporaryEvidence):e.evidenceId?`<button data-evidence="${esc(e.evidenceId)}">Open immutable evidence record</button>`:''}${raw('Claim support and authoritative facts',e.claims)}${raw('Contextual interpretation and transformation',e.turn??e.interpretation)}${raw('Generation audit and raw output',e.audit)}${raw('Reason codes', [...new Set(e.reasonCodes)])}</details></div></article>`;
}
export function renderAgent(view) {
 const state=view.agent, entries=state.entries.filter(e=>e.conversationId===state.activeConversationId), knowledge=state.knowledge, sandbox=knowledge?.kind==='upload';
 const draft=drafts.get(draftKey(view))??'', task=view.workflow.tasks.some(t=>t.status==='open');
 return `<div class="chat-heading"><div><div class="eyebrow">Your digital case worker</div><h1>Talk with Pathway.</h1></div><div class="buttons"><a href="#settings">Agent Settings</a><button data-new-conversation>New conversation</button></div></div>
 <div class="chat-workspace"><div class="knowledge-context"><div><strong>Using: ${esc(knowledge?.name??'Knowledge unavailable')}</strong><span>${knowledge?.sourceCount??0} sources · ${sandbox?'Selected for sandbox conversation':'Assigned governed case knowledge'} · Case DEMO-101</span></div><a href="#knowledge">Change knowledge →</a></div>
 <section class="conversation-stream" aria-label="Conversation history" tabindex="0">${entries.length?entries.map((e,i)=>i<entries.length-3?`<details class="older-turn"><summary>${esc(e.query.slice(0,110))}<span class="small muted">${esc(label(e.disposition))} · ${date(e.timestamp)}</span></summary>${answer(view,e)}</details>`:answer(view,e)).join(''):`<div class="agent-welcome"><img src="/mark.svg" alt=""><h2>${sandbox?'Let’s explore this document.':'What can we move forward today?'}</h2><p>${sandbox?'Ask about the document and inspect the exact supporting text. This temporary sandbox cannot establish case facts or authorize an action.':'The Alder case needs administrative follow-through. I can explain the evidence, help with the next step, or prepare a handoff.'}</p><p class="small muted">Choose a prompt to fill the message box, then press Send.</p><div class="suggestions">${(sandbox?['Summarize this document.','What does this document say about the next step?']:['What should happen next?','Summarize this case for a supervisor.','Draft a short email to the office requesting the missing document.']).map(t=>`<button data-agent-suggestion="${esc(t)}">${esc(t)}</button>`).join('')}</div></div>`}${sending?`<div class="pending-turn"><p class="user-turn">${esc(pending?.payload.text??'Saving your work product…')}</p><p role="status" class="response-progress">${esc(progressLabel)}</p></div>`:''}</section>
 <form id="agent-form" class="agent-composer" aria-busy="${sending}"><label for="agent-text">Message Pathway</label><div class="composer-input"><textarea id="agent-text" rows="2" maxlength="2000" placeholder="Ask a question or tell me what you need…" ${sending?'readonly':''}>${esc(draft)}</textarea><button type="submit" class="primary" ${sending?'disabled':''}>${sending?'Working…':'Send'}</button></div><div id="composer-error" role="alert" class="message bad" ${composerError?'':'hidden'}>${esc(composerError)}${composerError?'<button type="button" data-retry-message>Retry message</button>':''}</div><div class="composer-footer"><span>Enter to send · Shift+Enter for a new line</span><span>Generated answers need review · Nothing is sent</span></div></form>
 </div>
 ${!state.notice.acknowledgedAt?`<div class="session-notice"><p>${esc(state.notice.text)}</p><button data-acknowledge-notice>Acknowledge for this session</button></div>`:`<p class="small muted session-notice">Synthetic administrative demo · Session notice acknowledged</p>`}
 <div class="chat-secondary"><details class="card"><summary>Inspect case & conversation memory</summary><p>${esc(state.memoryPolicy)}</p><p>Temporary document conversations expire with their upload. Governed case records and answers remain durable.</p>${raw('Authoritative workflow, human decisions and effects',view.workflow)}${raw('Unverified conversation and work products',entries)}${state.conversations.filter(c=>c.archived_at).map(c=>raw('Earlier conversation · '+date(c.created_at),state.entries.filter(e=>e.conversationId===c.id))).join('')}</details><aside class="card"><h2>Continue the demonstration</h2><p class="small">Inspect a citation and the recommended next step above, then explore a human decision or knowledge governance.</p><div class="buttons"><a href="${task?'#review':'#workspace'}">${task?'Open human review':'Open case controls'} →</a><a href="#studio">Return to knowledge governance →</a><a href="#tour">Full technical walkthrough →</a></div><p class="small muted">Workflow stopping point: Documentation dependency resolved; prior authorization pending.</p></aside></div>`;
}
export function bindAgent({view,api,perform,refresh,render,toast}) {
 if(!view)return;
 const $=s=>document.querySelector(s), key=draftKey(view);
 const finishFocus=()=>{if(location.hash!=='#agent')return;render();const stream=$('.conversation-stream');if(stream){stream.scrollTop=stream.scrollHeight;const newest=[...stream.querySelectorAll('.answer-lead')].at(-1);if(newest&&newest.getBoundingClientRect().top<stream.getBoundingClientRect().top+12)stream.scrollTop-=stream.getBoundingClientRect().top+12-newest.getBoundingClientRect().top;}$('#agent-text')?.focus({preventScroll:true});$('#agent-form')?.scrollIntoView({block:'nearest',behavior:'instant'});};
 const submit=async(payload,legacy=false)=>{
  if(sending)return;
  const fingerprint=JSON.stringify({payload,legacy,key});
  if(!pending||pending.fingerprint!==fingerprint)pending={fingerprint,idempotencyKey:crypto.randomUUID(),payload,legacy,key};
  sending=true;composerError='';progressLabel='Understanding your message…';finishFocus();
  try {
   const response=await api(legacy?'/api/agent':'/api/conversation',{...payload,...(legacy?{synthetic:true}:{}),idempotencyKey:pending.idempotencyKey},legacy?undefined:stage=>{if(stageLabels[stage]){progressLabel=stageLabels[stage];const status=$('.response-progress');if(status)status.textContent=progressLabel;}});
   if(!legacy)drafts.delete(key);
   pending=null;
   // The mutation is already committed. Retain its response if the subsequent
   // state refresh fails; never resubmit a successfully saved message.
   if(!view.agent.entries.some(e=>e.id===response.id))view.agent.entries.push(response);
   view.agent.activeConversationId=response.conversationId;
   try {await refresh();}catch{composerError='Your message was saved. Refresh the page to reload the latest case state.';}
  }catch(error){if(location.hash==='#agent')composerError=error.message;}
  finally{sending=false;finishFocus();}
 };
 const sendText=(text,targetId)=>{if(!text.trim())return;drafts.set(key,text);return submit({text:text.trim(),...(targetId?{targetId}:{})});};
 $('#agent-text')?.addEventListener('input',e=>{drafts.set(key,e.target.value);});
 $('#agent-text')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!sending)$('#agent-form').requestSubmit();}});
 $('#agent-form')?.addEventListener('submit',e=>{e.preventDefault();void sendText($('#agent-text').value);});
 document.querySelectorAll('[data-agent-suggestion]').forEach(b=>b.addEventListener('click',()=>{drafts.set(key,b.dataset.agentSuggestion);$('#agent-text').value=b.dataset.agentSuggestion;$('#agent-text').focus();}));
 $('[data-retry-message]')?.addEventListener('click',()=>{if(pending)void submit(pending.payload,pending.legacy);});
 $('[data-acknowledge-notice]')?.addEventListener('click',()=>perform(async()=>{await api('/api/agent-preferences',{action:'acknowledge_notice'});await refresh();render();}));
 $('[data-new-conversation]')?.addEventListener('click',()=>void submit({operation:'new_conversation'},true));
 document.querySelectorAll('[data-clarify]').forEach(b=>b.addEventListener('click',()=>{const e=view.agent.entries.find(e=>e.id===b.dataset.clarify);if(e?.turn)void sendText(e.clarification.options.find(o=>o.value===b.dataset.choice).label);else void submit({operation:'clarify',targetId:b.dataset.clarify,choice:b.dataset.choice,generation:view.agent.provider.enabled?'model':'evidence'},true);}));
 document.querySelectorAll('[data-save-draft]').forEach(b=>b.addEventListener('click',()=>void submit({operation:'edit_draft',targetId:b.dataset.saveDraft,text:document.getElementById('draft-'+b.dataset.saveDraft).value},true)));
 document.querySelectorAll('[data-copy-draft]').forEach(b=>b.addEventListener('click',()=>perform(async()=>{const p=view.agent.entries.find(e=>e.id===b.dataset.copyDraft)?.workProduct;await navigator.clipboard.writeText(p?(p.subject?'Subject: '+p.subject+'\n\n':'')+p.body:'');toast('Copied. Nothing was sent.');})));
 document.querySelectorAll('[data-regenerate]').forEach(b=>b.addEventListener('click',()=>{const e=view.agent.entries.find(e=>e.id===b.dataset.regenerate);if(e)void submit({text:e.query,regenerateId:e.id});}));
 document.querySelectorAll('[data-feedback]').forEach(b=>b.addEventListener('click',()=>perform(async()=>{const scroll=$('.conversation-stream')?.scrollTop??0;await api('/api/agent-feedback',{entryId:b.dataset.feedback,rating:b.dataset.rating});await refresh();render();const stream=$('.conversation-stream');if(stream)stream.scrollTop=scroll;const note=document.getElementById('turn-'+b.dataset.feedback)?.querySelector('.turn-feedback span');if(note){note.tabIndex=-1;note.focus({preventScroll:true});}},'Feedback recorded.')));
 document.querySelectorAll('[data-product-prompt]').forEach(b=>b.addEventListener('click',()=>void sendText(b.dataset.productPrompt,b.dataset.target)));
 document.querySelectorAll('[data-memory-product]').forEach(b=>b.addEventListener('click',()=>void submit({operation:'save_memory',targetId:b.dataset.memoryProduct},true)));
 document.querySelectorAll('[data-review-product]').forEach(b=>b.addEventListener('click',()=>void submit({operation:'prepare_review',targetId:b.dataset.reviewProduct},true)));
 document.querySelectorAll('[data-inspect-product]').forEach(b=>b.addEventListener('click',()=>{const detail=document.getElementById('turn-'+b.dataset.inspectProduct)?.querySelector('.worker-turn > .advanced');if(detail){detail.open=true;detail.querySelector('summary')?.focus();}}));
}
