const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label = s => String(s ?? '').replaceAll('_',' ').replace(/^./, c=>c.toUpperCase());
let pickerTab = 'choose', fileDraft = null, parsedId = null;
export function renderKnowledge(view) {
 const uploads = view.knowledgeStudio.uploads, parsed = uploads.find(u=>u.id===parsedId);
 return `<section class="knowledge-picker"><div class="page-heading"><div><div class="eyebrow">Your first step</div><h1>Choose knowledge. Start talking.</h1><p>Bring a question. Pathway will keep the evidence and the next step in view.</p></div>${view.agent.entries.length?'<a href="#agent">Return to conversation →</a>':''}</div>
 <ol class="fast-steps" aria-label="Fast demonstration"><li aria-current="step">1. Choose knowledge</li><li>2. Ask a question</li><li>3. Inspect evidence & next step</li><li>4. Explore human review</li></ol>
 <div class="knowledge-options"><section class="card sample-choice"><span class="pill good">Recommended · ready to use</span><h2>Use sample knowledge</h2><p>Meet the synthetic Alder case. Find the missing document, understand the next step, and prepare a useful handoff.</p><button class="primary" data-choose-sample>Use sample knowledge →</button><p class="small muted">Preconfigured synthetic case · No upload or confirmation needed</p></section>
 <section class="card"><span class="eyebrow">Already governed</span><h2>Choose a Knowledge Pack</h2><p>See published packs, their source coverage, and which are currently permitted for this case.</p><button data-picker-tab="packs">Browse Knowledge Packs</button></section>
 <section class="card"><span class="eyebrow">Your document</span><h2>Upload a document</h2><p>Explore a TXT, Markdown, PDF or DOCX file in your own temporary sandbox.</p><button data-picker-tab="upload">Choose or drop a file</button><p class="small muted">1 MB maximum · Isolated to this session</p></section></div>
 ${pickerTab==='packs'?`<section class="card picker-section" id="picker-section"><h2>Knowledge Packs</h2><p class="small muted">Conversation selection uses existing permissions. It never publishes knowledge or changes the case assignment. Mandatory assigned knowledge remains included.</p><div class="pack-choices">${view.agent.packs.map(p=>`<article class="pack-choice"><div class="row"><h3>${esc(p.name)}</h3><span class="pill">${esc(label(p.status))}</span></div><p>${esc(p.description)}</p><p class="small muted">${p.sourceCount} sources · ${p.eligibleSourceCount} currently eligible · ${esc(p.version)}</p><dl class="kv small"><dt>Audience</dt><dd>${p.audiences.map(label).map(esc).join(', ')}</dd><dt>Permitted use</dt><dd>${p.permittedUses.map(label).map(esc).join(', ')}</dd></dl><button data-chat-pack="${esc(p.id)}" ${p.available?'':'disabled'}>Chat with this Knowledge Pack</button>${!p.available?'<p class="small muted">Current access, applicability or assignment does not permit this pack. Inspect it in Knowledge Studio.</p>':''}</article>`).join('')}</div></section>`:''}
 ${pickerTab==='upload'?`<section class="card picker-section" id="picker-section"><h2>Explore your document</h2><p>Uploads remain untrusted and sandbox-only. Original files, passages and their conversations expire with this four-hour session, or when you delete the upload.</p><form id="quick-upload"><label class="quick-drop" id="quick-drop" for="quick-file"><strong>Drop a file here, or choose a file</strong><span>TXT · Markdown · PDF · DOCX · up to 1 MB</span><input id="quick-file" type="file" accept=".txt,.md,.markdown,.pdf,.docx"></label><p id="quick-file-name" class="small">${esc(fileDraft?.name??'No file selected')}</p><label class="check-label"><input id="quick-confirm" type="checkbox" required>I confirm this new document is synthetic or authorized, with no patient information, confidential data or secrets.</label><button class="primary" type="submit">Parse document</button></form>${parsed?`<div class="parsed-handoff"><span class="pill good">Parsed · ${parsed.parsed.passages.length} passages</span><h3>${esc(parsed.metadata.sourceName)}</h3><p class="small">${esc(parsed.parsed.warnings.join(' '))}</p><button class="primary" data-chat-upload="${esc(parsed.id)}" ${parsed.status==='quarantined'?'disabled':''}>Chat with this document in the sandbox →</button>${parsed.status==='quarantined'?'<p class="message warn">Recognized untrusted instructions were quarantined. Inspect this document in Knowledge Studio.</p>':''}<details><summary>Preview extracted text</summary><div class="source-preview">${esc(parsed.parsed.text)}</div></details></div>`:''}${uploads.length?`<h3 class="mt-24">Your temporary documents</h3><div class="buttons">${uploads.map(u=>`<button data-chat-upload="${esc(u.id)}" ${u.status==='quarantined'?'disabled':''}>Chat with ${esc(u.metadata.sourceName)}</button>`).join('')}</div>`:''}</section>`:''}
 <p class="small muted picker-footnote">${esc(view.agent.notice.text)} <a href="#tour">Full technical walkthrough →</a></p></section>`;
}
export function renderSettings(view) {
 const s=view.agent.preferences.settings, permitted=view.role==='supervisor';
 const select=(id,title,values,value)=>`<div class="field"><label for="setting-${id}">${title}</label><select id="setting-${id}">${values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${esc(label(v))}</option>`).join('')}</select></div>`;
 return `<div class="page-heading"><div><div class="eyebrow">Administration</div><h1>Agent Settings</h1><p>Approved defaults keep the conversation simple. The Supervisor role can change these choices.</p></div><a href="#agent">Return to conversation →</a></div><div class="two-col"><section class="card"><h2>Conversation defaults</h2>${!permitted?'<p class="message">Switch the Demo role to Supervisor to approve changes.</p>':''}<form id="agent-settings"><fieldset ${permitted?'':'disabled'}><div class="metadata-grid">${select('synthesis','Default synthesis',['automatic','model','evidence'],s.synthesis)}${select('tone','Default tone',['concise','warm','formal'],s.tone)}${select('audience','Default audience',['case_manager','office','supervisor','crm'],s.audience)}${select('channel','Default draft channel',['email','sms','chat','voice','teams'],s.channel)}</div><p class="small muted">Automatic uses live grounded synthesis when the provider is configured. Evidence mode is explicit deterministic composition. A provider failure always pauses the answer.</p><fieldset><legend>Available audiences</legend>${['case_manager','office','supervisor','crm'].map(v=>`<label class="check-label"><input type="checkbox" name="setting-audience" value="${v}" ${s.audiences.includes(v)?'checked':''}>${esc(label(v))}</label>`).join('')}</fieldset><fieldset><legend>Available channels</legend>${['chat','email','sms','voice','teams'].map(v=>`<label class="check-label"><input type="checkbox" name="setting-channel" value="${v}" ${s.channels.includes(v)?'checked':''}>${esc(label(v))}</label>`).join('')}</fieldset><label class="check-label"><input type="checkbox" id="setting-drafting" ${s.drafting?'checked':''}>Allow unsent administrative communication drafts</label><button type="submit" class="primary">Approve defaults</button></fieldset></form></section><aside class="stack"><section class="card"><h2>Provider & grounding</h2><p>${view.agent.provider.enabled?'Live provider configured':'Live provider unavailable; automatic mode uses evidence composition'}</p><dl class="kv">${Object.entries(view.agent.policy).map(([key,value])=>`<dt>${esc(label(key))}</dt><dd>${esc(value)}</dd>`).join('')}</dl><p class="small muted">These constraints are fixed. Model changes require a reviewed server deployment; chat settings cannot grant new authority.</p></section><section class="card"><h2>Session notice</h2><p>${esc(view.agent.notice.text)}</p><p class="small muted">${view.agent.notice.acknowledgedAt?'Acknowledged for this session.':'Acknowledgement is optional. Content screening applies to every request.'}</p></section></aside></div>`;
}
export function bindKnowledge({view,api,perform,refresh,render,canChange=()=>true}) {
 const navigate=async selection=>{if(!canChange())throw new Error('Wait for the current response before changing knowledge.');await api('/api/agent-preferences',{action:'select',selection});await refresh();location.hash='agent';render();document.getElementById('agent-text')?.focus();};
 document.querySelectorAll('[data-choose-sample]').forEach(b=>b.addEventListener('click',()=>perform(()=>navigate({kind:'sample'}))));
 document.querySelectorAll('[data-chat-pack]').forEach(b=>b.addEventListener('click',()=>perform(()=>navigate({kind:'pack',releaseId:b.dataset.chatPack}))));
 document.querySelectorAll('[data-chat-upload]').forEach(b=>b.addEventListener('click',()=>perform(()=>navigate({kind:'upload',uploadId:b.dataset.chatUpload}))));
 document.querySelectorAll('[data-picker-tab]').forEach(b=>b.addEventListener('click',()=>{pickerTab=b.dataset.pickerTab;render();document.getElementById('picker-section')?.scrollIntoView({block:'start'});}));
 const showFile=file=>{fileDraft=file;document.getElementById('quick-file-name').textContent=file?.name??'No file selected';document.getElementById('quick-confirm').checked=false;};
 document.getElementById('quick-file')?.addEventListener('change',e=>showFile(e.target.files[0]));
 const drop=document.getElementById('quick-drop');drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('dragover');});drop?.addEventListener('dragleave',()=>drop.classList.remove('dragover'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragover');showFile(e.dataTransfer.files[0]);});
 document.getElementById('quick-upload')?.addEventListener('submit',e=>{e.preventDefault();perform(async()=>{const file=fileDraft;if(!file)throw new Error('Choose a document first.');if(file.size>1048576)throw new Error('Choose a file no larger than 1 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const u=await api('/api/studio-upload',{name:file.name,base64:btoa(binary),synthetic:document.getElementById('quick-confirm').checked});parsedId=u.id;fileDraft=null;await refresh();render();document.querySelector('.parsed-handoff button')?.focus();});});
 document.getElementById('agent-settings')?.addEventListener('submit',e=>{e.preventDefault();perform(async()=>{const value=id=>document.getElementById('setting-'+id).value;const settings={synthesis:value('synthesis'),tone:value('tone'),audience:value('audience'),channel:value('channel'),drafting:document.getElementById('setting-drafting').checked,audiences:[...document.querySelectorAll('[name=setting-audience]:checked')].map(n=>n.value),channels:[...document.querySelectorAll('[name=setting-channel]:checked')].map(n=>n.value)};await api('/api/agent-preferences',{action:'settings',settings,revision:view.agent.preferences.revision});await refresh();render();},'Conversation defaults approved.');});
}
