const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=[
 ['Bring a synthetic document','studio','sandbox','Download the synthetic sample in Upload & review, then drag it into the drop zone. Confirm the content declaration and choose Parse into sandbox.'],
 ['Inspect passages and metadata','studio','sandbox','Open Passage 2 and compare its exact text with the preserved original. Use synthetic case scope to propose this demo’s metadata, review it, then Save metadata for review. Unknown never means unrestricted.'],
 ['Ask in the sandbox','studio','test','Select the temporary sandbox and your upload. Ask “What document does this guide request?” Hybrid is the default. If no provider is configured, inspect the explicit pause, then deliberately select and acknowledge lexical exploration to inspect exact passages.'],
 ['Review and publish','studio','sandbox','Submit the saved revision. Switch Demo role to Knowledge Reviewer. Approve after inspecting the checks, then separately publish the immutable release. Each confirmation shows the impact.'],
 ['Assign the release','studio','packs','Assign the newly published release to DEMO-101. Inspect its plan, audience and permitted use. Publication alone did not change case authority.'],
 ['Start a continuing conversation','agent',null,'Choose sample or assigned knowledge, then ask “What should happen next?” Follow with “Why?” or a question in your own words. Refresh or navigate away and return: both the conversation and operational case persist. New semantic inputs require the configured provider.'],
 ['Read the answer and next step','agent',null,'Read the direct answer first. Expand Sources behind this answer to inspect an exact passage. Next step and case context separately shows the owner, recommendation and permissions.'],
 ['Prepare work products','agent',null,'Ask “Draft a short email to the office requesting the missing document.” Then “Make that warmer and shorter,” or request a case-manager handoff. Copy includes only the subject and body. Record a synthetic voice or Teams transcript to inspect administrative cues and unverified memory.'],
 ['Introduce ambiguity','workspace',null,'As Office, identify the documentation dependency and dispatch the generic simulated follow-up. Choose Introduce an ambiguity. In chat, leave the recipient explicitly undecided between an office contact limited to generic SMS and a case manager who accepts detailed email. The focused recipient question clarifies the conversation; it cannot resolve an operational task.'],
 ['Resolve through the assigned role','review',null,'Switch to Manager for the clarification task and choose Clarify and resume collection. Return as Office, simulate document receipt, verify the exact package in Human review, dispatch it, and record the receiving acknowledgment. Prior authorization stays pending.'],
 ['Retire the supporting source','studio','sources','As Knowledge Reviewer, find the uploaded source, inspect its release and historical answers, and retire its governed version. Confirm the future impact. The control changes to Retirement recorded.'],
 ['Observe the safe pause','agent',null,'Ask the case question again. The new answer pauses. Expand the earlier answer: its exact passages and evidence hash remain unchanged. Uploading a sandbox replacement cannot restore authority.'],
];
const key=view=>'pathway-tour-v1:'+view.demoId;
function saved(view){try{return JSON.parse(sessionStorage.getItem(key(view))||'[]');}catch{return [];}}
export function tourBanner(view){const done=saved(view);return `<a class="tour-banner" href="#tour"><span><strong>3–5 minute portfolio journey</strong> · ${done.length} of 12 steps checked</span><span>Open guide →</span></a>`;}
export function renderTour(view){const done=saved(view);return `<div class="page-heading"><div><div class="eyebrow">A guided portfolio journey</div><h1>From a document to accountable follow-through.</h1><p>Allow 3–5 minutes after the service is awake. Follow one synthetic case across knowledge, conversation and human judgment.</p></div></div><section class="card tour-intro"><h2>Evidence guides the worker. People retain authority.</h2><p>Case memory, conversation and five simulated channels are connected. Source support, applicability, communication permission, action permission and the payer’s decision remain separate.</p><p class="message ${view.agent.provider.enabled?'good':'warn'}">${view.agent.provider.enabled?'Live embedding and synthesis adapters are configured with bounded server budgets. Choose knowledge and start chatting; no style setup is required.':'Live model generation is not configured. Cached synthetic case questions still work. New semantic questions and new upload vectors pause explicitly. Lexical sandbox exploration is a separate, acknowledged mode; it does not prove live model quality.'}</p><p class="small muted">Checklist progress is your own navigation aid, saved in this browser tab. A checkmark does not record approval or execute work. Each real synthetic decision is saved by its own control.</p><a href="#evaluation">Inspect measured checks and limitations →</a></section><ol class="tour-steps">${steps.map(([title,route,tab,description],i)=>`<li class="card tour-step ${done.includes(i)?'checked':''}"><span class="tour-number">${String(i+1).padStart(2,'0')}</span><div><h2>${esc(title)}</h2><p>${esc(description)}</p><div class="buttons"><button class="primary" data-tour-route="${route}" ${tab?`data-tour-tab="${tab}"`:''}>Open this step</button><label class="check-label"><input type="checkbox" data-tour-check="${i}" ${done.includes(i)?'checked':''}>I inspected this step</label></div></div></li>`).join('')}</ol><section class="boundary"><h2>The stopping condition</h2><p>Documentation dependency resolved; prior authorization pending.</p></section>`;}
export function bindTour({view,navigate,render}){document.querySelectorAll('[data-tour-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.tourRoute,b.dataset.tourTab)));document.querySelectorAll('[data-tour-check]').forEach(b=>b.addEventListener('change',()=>{const done=saved(view).filter(n=>n!==Number(b.dataset.tourCheck));if(b.checked)done.push(Number(b.dataset.tourCheck));sessionStorage.setItem(key(view),JSON.stringify(done));render();}));}
export async function loadEvaluation(){const response=await fetch('/evaluation.json');if(!response.ok)throw new Error('The evaluation report is unavailable.');return response.json();}
function renderContextualComparison(c){if(!c)return '';const rows=[['Previous live pipeline',c.baseline],['Contextual pipeline',c.redesigned]];return `<section class="card mt-24"><h2>Frozen conversation comparison</h2><p>${c.redesigned?'The same twelve synthetic prompts were run through both pipelines. Mechanical checks and semantic review are reported separately.':'The previous live pipeline is recorded. The contextual pipeline has passed local contract checks; its paired live run is still pending.'}</p><div class="evaluation-table"><table><caption>Actual public browser conversations · model identity and raw results retained</caption><thead><tr><th scope="col">Pipeline</th><th scope="col">Answered turns</th><th scope="col">Unneeded clarification</th><th scope="col">Email word reduction</th><th scope="col">Median response</th></tr></thead><tbody>${rows.map(([name,m])=>`<tr><th scope="row">${esc(name)}</th>${m?`<td>${m.acceptedTurns}/${m.turns}</td><td>${m.unnecessaryClarifications}</td><td>${m.reductionPercent===null?'Unavailable':m.reductionPercent.toFixed(1)+'%'}</td><td>${m.medianLatencyMs===null?'Unavailable':(m.medianLatencyMs/1000).toFixed(1)+' s'}</td>`:'<td colspan="4">Live measurement pending</td>'}</tr>`).join('')}</tbody></table></div><p class="small muted">${esc(c.manualSemanticReview?.summary??'Independent semantic quality is not established by these mechanical checks.')}</p>${c.latestCorrectionEvidence?`<p>${esc(c.latestCorrectionEvidence.summary)}</p>`:''}<details><summary>Conversation results and limitations</summary><pre>${esc(JSON.stringify(c,null,2))}</pre></details></section>`;}
export function renderEvaluation(report){if(!report)return '<section class="card"><h1>Evaluation report</h1><p role="status">Loading the published measurement record…</p></section>';return `<div class="page-heading"><div><div class="eyebrow">Measured evidence, explicit limits</div><h1>What has actually been verified.</h1><p>Automated contract checks, cached retrieval measurements and live model quality are separate categories.</p></div></div><section class="card"><h2>Digital worker verification</h2><p>${esc(report.summary)}</p><p class="small muted">Measured ${esc(new Date(report.timestamp).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Denver',timeZoneName:'short'}))} · ${esc(report.environment)}</p><div class="evaluation-table"><table><caption>Recorded verification commands</caption><thead><tr><th scope="col">Suite</th><th scope="col">Result</th><th scope="col">Duration</th></tr></thead><tbody>${(report.suites||[]).map(s=>`<tr><th scope="row">${esc(s.name)}</th><td>${s.passed?'Passed':'Failed'}${s.tests!=null?` · ${s.tests} checks`:''}</td><td>${(s.durationMs/1000).toFixed(1)} s</td></tr>`).join('')}</tbody></table></div><p class="small muted">Suite duration is test execution time, not answer latency. Unit fixtures and synthetic vectors do not establish live model quality.</p></section>${renderContextualComparison(report.contextualComparison)}<div class="two-col mt-24"><section class="card"><h2>Retrieval</h2><p>${esc(report.retrieval?.summary)}</p><p class="small">Provider/model: ${esc(report.retrieval?.model)}</p><p class="small muted">${esc(report.retrieval?.limitations)}</p></section><section class="card"><h2>Generation, latency and cost</h2><p>${esc(report.generation?.summary)}</p><p class="small">Configured adapter: ${esc(report.generation?.model)}</p><p class="small muted">${esc(report.generation?.cost)}</p><p>Each answer’s advanced audit records its actual method, model identity, request count, token usage, elapsed composition time and estimated cost when available.</p></section></div><section class="card mt-24"><h2>Limits and unverified claims</h2><ul>${(report.limitations||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><details><summary>Exact published measurement record</summary><pre>${esc(JSON.stringify(report,null,2))}</pre></details></section>`;}
